CREATE TABLE demo_dw.`ads_ops_ord_line_rel_td` (
  `ord_rel_id` STRING COMMENT '订单行关系ID，MD5(Tangbuy内部订单子单号+DS订单行ID)',
  `is_ds_ord` BIGINT COMMENT '是否DS插件订单: 1-能关联到DS订单行宽表, 0-主站订单',
  `data_src` STRING COMMENT 'Tangbuy内部子单数据来源',
  `ord_no` STRING COMMENT 'Tangbuy内部订单号',
  `ord_line_no` STRING COMMENT 'Tangbuy内部订单子单号(item_no)，本表粒度',
  `ds_ord_no` STRING COMMENT '关联DS订单ID',
  `ds_ord_line_no` STRING COMMENT '关联DS订单行ID',
  `out_ord_id` STRING COMMENT '三方平台订单ID',
  `out_ord_no` STRING COMMENT '三方平台订单号',
  `out_ord_line_id` STRING COMMENT '三方平台订单行ID',
  `pay_no` STRING COMMENT 'Tangbuy内部订单支付单号',
  `pur_no` STRING COMMENT 'Tangbuy内部子单采购单号',
  `cmpny_id` BIGINT COMMENT '采购公司ID',
  `ord_stat` BIGINT COMMENT 'Tangbuy内部订单状态: 0-待付款, 1-待接单, 2-处理中, 3-转单中, 4-取消订购, 5-邮费补款, 6-风控中, 7-撤单退款, 8-支付中, 9-已完成',
  `ord_stat_nm` STRING COMMENT 'Tangbuy内部订单状态名称',
  `ord_type_cd` BIGINT COMMENT 'Tangbuy内部订单类型编码: 0/1-普通接单池, 2/3-特殊接单池, 4-巴拿马接单池, 5-用户接单池, 6-用户转运, 7-1688API, 8-YINO接单池',
  `ds_ord_stat` BIGINT COMMENT 'DS订单状态: 1-待处理, 2-待支付, 3-备货中, 4-待发货, 5-待送达, 6-已完结, 9-已取消, 10-已退款, 11-已失效',
  `ds_ord_stat_nm` STRING COMMENT 'DS订单状态名称',
  `ds_ord_type_cd` BIGINT COMMENT 'DS订单类型编码: 1-代发, 2-直购备货, 3-直购直发, 4-询盘备货, 5-询盘直发',
  `ord_line_stat` BIGINT COMMENT 'Tangbuy内部订单子单状态: -2-支付中, -1-待支付, 0-待接单, 2-待补款, 5-已发货, 6-分开发货, 8-已签收, 9-已到货, 10-已入库, 11-作废, 12-销毁, 14-待确认, 16-退货等待中, 17-换货等待中, 18-退货处理中, 19-换货处理中, 20-退货完成, 21-换货作废, 22-已订购, 23-处理中, 24-取消订购, 25-异常订单, 26-退货等待退款, 27-换货等待卖家发货, 28-出库中, 29-出库打包完毕, 30-寄送海外, 31-已收到货, 33-风控审核, 34-已撤单, 35-冻结列表, 36-预定补款, 37-等待出库, 38-退款审核中, 39-拒签商品, 40-拒签完成, 41-异常未入, 42-异常已入, 45-已签收待处理, 46-巴拿马待生成, 47-巴拿马待支付, 49-放弃商品, 50-强制完成, 51-等待卖家同意退货, 52-等待卖家同意换货, 53-退包作废, 54-1688待生成, 55-1688待支付, 56-yino待生成, 57-yino待支付, 58-仓库处理中',
  `ord_line_stat_nm` STRING COMMENT 'Tangbuy内部订单子单状态名称',
  `cfm_stat` BIGINT COMMENT '待确认状态',
  `rtn_stat` BIGINT COMMENT '退换货状态',
  `sales_type_cd` BIGINT COMMENT '销售类型编码: 0-正常订单, 2-爆品商品, 3-询盘订单, 4-插件订单, 5-插件询盘备货订单, 6-插件询盘直发订单, 7-插件直购订单, 8-插件直购备货订单',
  `abn_type_cd` BIGINT COMMENT '异常类型编码',
  `cart_pur_type_cd` BIGINT COMMENT '购物车订购类型: 0-未订购, 1-已订购',
  `show_way_cd` BIGINT COMMENT '展示方式: 0-不展示, 1-我的仓库, 2-我的备货',
  `is_ord_del` BIGINT COMMENT 'Tangbuy内部订单是否删除: 0-否, 1-是',
  `is_line_del` BIGINT COMMENT 'DS订单行是否删除: 0-否, 1-是',
  `is_expd` BIGINT COMMENT '是否加急: 0-否, 1-是',
  `is_exprs_dlyd` BIGINT COMMENT '是否已快递发货: 0-否, 1-是',
  `is_need_cfm` BIGINT COMMENT '是否需要确认: 0-否, 1-是',
  `is_deferred` BIGINT COMMENT '是否延期处理: 0-否, 1-是',
  `cxl_rsn` STRING COMMENT 'DS订单取消原因',
  `cxl_rsn_id` BIGINT COMMENT 'DS订单取消原因ID',
  `ccy` STRING COMMENT '下单币种',
  `ds_ccy` STRING COMMENT 'DS三方订单币种',
  `dev` STRING COMMENT '下单设备',
  `sys_tag` STRING COMMENT '系统标记',
  `ord_rmk` STRING COMMENT '三方订单用户备注',
  `rmk` STRING COMMENT 'DS子单备注',
  `usr_id` BIGINT COMMENT '用户ID',
  `usr_nm` STRING COMMENT '用户姓名',
  `email` STRING COMMENT '用户邮箱',
  `usr_cntry_cd` STRING COMMENT '用户注册国家简码',
  `usr_cntry_nm` STRING COMMENT '用户注册国家名称',
  `usr_lang` STRING COMMENT '用户语言偏好',
  `usr_stat` BIGINT COMMENT '用户账户状态: 0-无效, 1-有效',
  `is_usr_frz` BIGINT COMMENT '用户是否冻结: 0-否, 1-是',
  `is_usr_risk` BIGINT COMMENT '用户是否风险用户: 0-否, 1-是',
  `usr_lvl_id` BIGINT COMMENT '用户会员等级ID',
  `usr_lvl_nm` STRING COMMENT '用户会员等级名称',
  `usr_lvl` BIGINT COMMENT '用户会员等级值',
  `usr_vip_lvl` BIGINT COMMENT '订单侧用户VIP等级',
  `shop_id` STRING COMMENT 'Tangbuy/接单店铺ID',
  `shop_nm` STRING COMMENT 'Tangbuy/接单店铺名称',
  `shop_url` STRING COMMENT 'Tangbuy/接单店铺链接',
  `ds_shop_id` STRING COMMENT 'DS三方店铺ID',
  `ds_shop_nm` STRING COMMENT 'DS三方店铺名称',
  `splr_shop_id` STRING COMMENT '供应商店铺ID',
  `splr_shop_nm` STRING COMMENT '供应商店铺名称',
  `splr_shop_url` STRING COMMENT '供应商店铺URL',
  `shop_pltf_cd` STRING COMMENT '店铺平台编码: SHOPIFY/TIKTOK/WOOCOMMERCE',
  `slr_nm` STRING COMMENT '卖家名称',
  `pur_usr_nm` STRING COMMENT '采购员名称',
  `pur_usr_id` STRING COMMENT '采购员ID',
  `pur_usr_dept` STRING COMMENT '采购员部门',
  `bd_usr_nm` STRING COMMENT 'BD用户名(DS订单行优先，主站订单行兜底)',
  `auth_rel_id` BIGINT COMMENT '店铺授权关系ID',
  `auth_stat` BIGINT COMMENT '店铺授权状态ID: 0-禁用, 1-启用, -1-未知',
  `auth_stat_nm` STRING COMMENT '店铺授权状态名称',
  `auth_shop_url` STRING COMMENT '授权店铺URL/域名',
  `auth_slr_nm` STRING COMMENT '授权店铺卖家名称',
  `auth_shop_rgn_cd` STRING COMMENT '授权店铺所在区域编码',
  `is_auth_shop_unreachable` BIGINT COMMENT '授权店铺是否无法访问: 0-否, 1-是',
  `auth_shop_unreachable_rsn` STRING COMMENT '授权店铺无法访问原因',
  `is_auth_del` BIGINT COMMENT '授权店铺是否删除: 0-否, 1-是',
  `item_id` STRING COMMENT 'Tangbuy商品ID',
  `sku_id` STRING COMMENT 'Tangbuy SKU ID',
  `item_nm` STRING COMMENT 'Tangbuy商品名称',
  `item_nm_cn` STRING COMMENT 'Tangbuy商品中文名称',
  `item_attr` STRING COMMENT 'Tangbuy商品属性',
  `item_attr_cn` STRING COMMENT 'Tangbuy商品属性中文',
  `item_url` STRING COMMENT 'Tangbuy商品链接',
  `item_img` STRING COMMENT 'Tangbuy商品图片',
  `item_type_cd` BIGINT COMMENT 'Tangbuy商品类型: 1-普通商品, 2-组合商品',
  `item_aud_stat` BIGINT COMMENT '商品品牌审核状态: 0-未审核, 1-审核通过',
  `ds_item_cnt` BIGINT COMMENT 'DS三方商品数量',
  `item_dim_id` BIGINT COMMENT '三方商品维度ID',
  `item_stat_cd` STRING COMMENT '三方商品状态编码: ACTIVE/DRAFT/ARCHIVED',
  `ctgy_id` BIGINT COMMENT 'Tangbuy内部子单商品分类ID',
  `lvl1_ctgy_id` BIGINT COMMENT 'Tangbuy内部子单一级类目ID',
  `lvl1_ctgy_nm` STRING COMMENT 'Tangbuy内部子单一级类目名称',
  `lvl2_ctgy_id` BIGINT COMMENT 'Tangbuy内部子单二级类目ID',
  `lvl2_ctgy_nm` STRING COMMENT 'Tangbuy内部子单二级类目名称',
  `lvl3_ctgy_id` BIGINT COMMENT 'Tangbuy内部子单三级类目ID',
  `lvl3_ctgy_nm` STRING COMMENT 'Tangbuy内部子单三级类目名称',
  `lvl4_ctgy_id` BIGINT COMMENT 'Tangbuy内部子单四级类目ID',
  `lvl4_ctgy_nm` STRING COMMENT 'Tangbuy内部子单四级类目名称',
  `dcl_cn_nm` STRING COMMENT 'Tangbuy内部子单类目申报中文名称',
  `dcl_en_nm` STRING COMMENT 'Tangbuy内部子单类目申报英文名称',
  `cstm_hs_cd` STRING COMMENT 'Tangbuy内部子单类目海关HS编码',
  `cmb_item_id` STRING COMMENT '组合商品ID',
  `cmb_item_nm` STRING COMMENT '组合商品名称',
  `cmb_item_attr` STRING COMMENT '组合商品属性',
  `cmb_item_img` STRING COMMENT '组合商品图片',
  `cmb_item_url` STRING COMMENT '组合商品URL',
  `item_rmk` STRING COMMENT 'Tangbuy内部子单商品备注',
  `item_rmk_img` STRING COMMENT 'Tangbuy内部子单备注图片',
  `usr_rmk` STRING COMMENT 'Tangbuy内部子单用户备注',
  `ord_cnt` BIGINT COMMENT 'Tangbuy内部子单商品数量',
  `prc` DECIMAL(18,4) COMMENT 'Tangbuy内部子单商品单价',
  `pur_prc` DECIMAL(18,4) COMMENT 'Tangbuy内部子单采购价格',
  `pur_amt` DECIMAL(18,4) COMMENT 'DS子单采购金额',
  `post_fee` DECIMAL(18,4) COMMENT 'DS子单国内邮费',
  `ord_amt` DECIMAL(18,4) COMMENT 'Tangbuy内部子单商品订单金额(采购价×数量，原币)',
  `ds_ord_amt` DECIMAL(18,4) COMMENT 'DS三方订单行金额(原币)',
  `ds_ord_amt_cny` DECIMAL(18,4) COMMENT 'DS三方订单行金额(人民币，按ccy汇率折算)',
  `vrtl_prc` DECIMAL(18,4) COMMENT '虚拟价格',
  `disc_amt` DECIMAL(18,4) COMMENT 'Tangbuy内部子单优惠金额',
  `item_xtra_amt` DECIMAL(18,4) COMMENT 'Tangbuy内部子单商品已补款金额',
  `item_pend_xtra_amt` DECIMAL(18,4) COMMENT 'Tangbuy内部子单商品待补款金额',
  `booked_xtra_amt` DECIMAL(18,4) COMMENT 'Tangbuy内部子单预定补款金额',
  `rtn_amt` DECIMAL(18,4) COMMENT 'Tangbuy内部子单商品退款金额',
  `rtn_fee` DECIMAL(18,4) COMMENT 'Tangbuy内部子单退换货手续费',
  `back_post_amt` DECIMAL(18,4) COMMENT 'Tangbuy内部子单寄回邮费',
  `ins_back_amt` DECIMAL(18,4) COMMENT 'Tangbuy内部子单保险已赔金额',
  `custom_fee` DECIMAL(18,4) COMMENT 'Tangbuy内部子单定制服务费',
  `ref_cnt` BIGINT COMMENT 'DS子单已退款数量',
  `crsh_cnt` BIGINT COMMENT 'DS子单碰撞库存数量',
  `crsh_ref_cnt` BIGINT COMMENT 'DS子单库存碰撞退款数量',
  `pur_sugg_prc` DECIMAL(18,4) COMMENT '采购建议价',
  `pur_sugg_post_prc` DECIMAL(18,4) COMMENT '采购建议邮费',
  `splr_type_cd` STRING COMMENT '供应商类型编码',
  `pur_type_cd` BIGINT COMMENT '阶梯价类型: 0-不享受, 1-享受',
  `pur_rate` DECIMAL(18,4) COMMENT '组合商品计算比例',
  `splr_item_id` STRING COMMENT '1688上游供应商商品ID',
  `tot_gmv` DECIMAL(18,4) COMMENT '订单行整体GMV(ord_gmv+pkg_gmv；退款/退货/退包/取消/作废/异常/风控等非正常订单或包裹状态置0)',
  `ord_gmv` DECIMAL(18,4) COMMENT '订单GMV(DS订单取pur_amt；TB订单取item_ord_amt-disc_amt；各分量NVL兜底0，下限GREATEST取0；非正常状态置0)',
  `pkg_gmv` DECIMAL(18,4) COMMENT '包裹GMV(取订单行分摊预估总费用alloc_tot_pre_amt；NVL兜底0，下限GREATEST取0；非正常状态置0)',
  `pkg_no` STRING COMMENT 'Tangbuy内部子单当前包裹单号',
  `pkg_type_cd` STRING COMMENT '包裹类型编码',
  `pkg_wrap_cd` STRING COMMENT '包裹包装类型: 极简包装/纸箱包装/未知包装',
  `pkg_stat` BIGINT COMMENT '包裹主状态: 0-待处理, 1-处理中, 2-出库中, 3-已出库, 4-已打包, 5-已称重, 6-已打印运单号, 7-已验证, 8-已交接, 9-已发货, 20-确认收货',
  `pkg_stat_nm` STRING COMMENT '包裹主状态名称',
  `pkg_pay_stat` BIGINT COMMENT '包裹支付状态: 0-待付款, 1-处理中, 2-已支付, 3-已通知, 4-已退款, 5-失败, 6-已取消',
  `pkg_bag_stat` BIGINT COMMENT '包裹退包状态: 0-正常包裹, 1-国内退包, 2-国外退包, 3-取消包裹, 4-包裹待补款',
  `pkg_bag_stat_nm` STRING COMMENT '包裹退包状态名称',
  `pkg_exprs_no` STRING COMMENT '包裹快递单号',
  `pkg_exprs_nm` STRING COMMENT '包裹快递公司名称',
  `exprs_no` STRING COMMENT 'Tangbuy内部子单快递单号',
  `exprs_id` STRING COMMENT 'Tangbuy内部子单快递公司编号',
  `exprs_nm` STRING COMMENT 'Tangbuy内部子单快递公司名称',
  `pkg_line_nm` STRING COMMENT '包裹物流线路名称',
  `pkg_line_id` STRING COMMENT '包裹物流线路ID',
  `pkg_rcv_cntry_cd` STRING COMMENT '包裹收件国家ISO 3166-1 alpha-2代码',
  `pkg_rcv_cntry` STRING COMMENT '包裹收件国家英文标准名称',
  `pkg_rcv_cntry_cn` STRING COMMENT '包裹收件国家中文名称',
  `pkg_rcv_area` STRING COMMENT '包裹收件地区',
  `pkg_rcv_city` STRING COMMENT '包裹收件城市',
  `rcv_nm` STRING COMMENT '收货人姓名',
  `wh_id` BIGINT COMMENT '仓库ID',
  `wh_nm` STRING COMMENT '仓库名称',
  `bin_no` STRING COMMENT 'Tangbuy内部子单库位号',
  `ml_lmt` STRING COMMENT 'Tangbuy内部子单邮限',
  `wt` DECIMAL(18,4) COMMENT 'Tangbuy内部子单商品重量',
  `vol_desc` STRING COMMENT 'Tangbuy内部子单体积描述(长宽高)',
  `line_vol` DECIMAL(18,4) COMMENT 'Tangbuy内部子单体积(cm³，由vol_desc解析)',
  `pred_wt` DECIMAL(18,4) COMMENT '包裹预测重量',
  `actl_wt` DECIMAL(18,4) COMMENT '包裹实际重量',
  `diff_wt` DECIMAL(18,4) COMMENT '包裹重量差异',
  `item_wt` DECIMAL(18,4) COMMENT '包裹商品总重量',
  `pkg_actl_wt` DECIMAL(18,4) COMMENT '包裹打包后实际重量',
  `pkg_len` DECIMAL(18,4) COMMENT '包裹长度(cm)',
  `pkg_wid` DECIMAL(18,4) COMMENT '包裹宽度(cm)',
  `pkg_hgt` DECIMAL(18,4) COMMENT '包裹高度(cm)',
  `is_vol_wt_on` BIGINT COMMENT '包裹是否使用体积重: 0-否, 1-是',
  `fee_alloc_rate` DECIMAL(18,4) COMMENT '包裹费用分摊比例(内部子单商品订单金额/包裹内内部子单商品订单金额合计)',
  `wt_alloc_rate` DECIMAL(18,4) COMMENT '包裹重量分摊比例(内部子单重量/包裹内内部子单重量合计)',
  `vol_alloc_rate` DECIMAL(18,4) COMMENT '包裹体积分摊比例(内部子单体积/包裹内内部子单体积合计)',
  `alloc_tot_pre_amt` DECIMAL(18,4) COMMENT '分摊预估总费用',
  `alloc_tot_actl_amt` DECIMAL(18,4) COMMENT '分摊实际总费用',
  `alloc_tech_srv_pre_fee` DECIMAL(18,4) COMMENT '分摊预估技术服务费',
  `alloc_tech_srv_actl_fee` DECIMAL(18,4) COMMENT '分摊实际技术服务费',
  `alloc_ins_amt` DECIMAL(18,4) COMMENT '分摊保险费',
  `alloc_diff_amt` DECIMAL(18,4) COMMENT '分摊费用差额',
  `alloc_succ_diff_amt` DECIMAL(18,4) COMMENT '分摊成功交易差额',
  `alloc_cpn_amt` DECIMAL(18,4) COMMENT '分摊优惠券金额',
  `alloc_disc_amt` DECIMAL(18,4) COMMENT '分摊折扣金额',
  `alloc_dep_amt` DECIMAL(18,4) COMMENT '分摊预存款',
  `alloc_actl_dep_amt` DECIMAL(18,4) COMMENT '分摊实际存款',
  `alloc_wt` DECIMAL(18,4) COMMENT '分摊重量(kg)，is_vol_wt_on=0时有效',
  `alloc_vol` DECIMAL(18,4) COMMENT '分摊体积(cm³)，is_vol_wt_on=1时有效',
  `pkg_biz_rmk` STRING COMMENT '包裹业务备注',
  `ord_crt_time` DATETIME COMMENT 'Tangbuy内部订单主单创建时间',
  `ord_pend_time` DATETIME COMMENT 'Tangbuy内部订单接单时间',
  `ord_submit_time` DATETIME COMMENT '履约节点-订单提交时间',
  `pend_pay_time` DATETIME COMMENT '履约节点-待支付时间',
  `pay_time` DATETIME COMMENT '履约节点-已支付时间',
  `pur_time` DATETIME COMMENT '履约节点-已订购时间',
  `wh_stock_in_time` DATETIME COMMENT '履约节点-入库时间',
  `stor_out_time` DATETIME COMMENT 'Tangbuy内部子单入库超期时间',
  `pend_ob_time` DATETIME COMMENT '履约节点-等待出库时间',
  `ob_ing_time` DATETIME COMMENT '履约节点-正在出库中时间',
  `pkg_cmpl_time` DATETIME COMMENT '履约节点-出库打包完毕时间',
  `pkg_snd_time` DATETIME COMMENT '包裹发货时间',
  `snd_ovs_time` DATETIME COMMENT '履约节点-已寄送海外时间',
  `arv_time` DATETIME COMMENT '履约节点-已到货时间',
  `sign_time` DATETIME COMMENT '履约节点-已签收时间',
  `rcv_time` DATETIME COMMENT '履约节点-已收到货时间',
  `pkg_dly_time` DATETIME COMMENT '包裹妥投时间',
  `pkg_back_time` DATETIME COMMENT '包裹退回时间',
  `ord_cxl_time` DATETIME COMMENT '履约节点-取消订购时间',
  `rtn_req_time` DATETIME COMMENT '履约节点-申请退货时间',
  `rtn_cmpl_time` DATETIME COMMENT '履约节点-退货完成时间',
  `ord_ref_time` DATETIME COMMENT '履约节点-订单退款时间',
  `usr_crt_time` DATETIME COMMENT '用户注册时间',
  `crt_time` DATETIME COMMENT 'DS订单行创建时间',
  `upd_time` DATETIME COMMENT 'DS订单行更新时间',
  `rmk_time` DATETIME COMMENT 'Tangbuy内部子单备注添加时间',
  `auth_shop_crt_time` DATETIME COMMENT '授权店铺创建时间',
  `auth_crt_time` DATETIME COMMENT '授权创建时间',
  `auth_upd_time` DATETIME COMMENT '授权更新时间',
  `auth_revoke_time` DATETIME COMMENT '用户撤销店铺授权时间'
)
COMMENT '运营管理集市-订单分析-订单行关系宽表-历史截至当日(基于Tangbuy订单行DWS与DS订单行DWS full join；同名字段优先取Tangbuy订单行宽表，缺失取DS订单行宽表同名字段)'
PARTITIONED BY (
  `ds` STRING NOT NULL COMMENT '分区日期 yyyyMMdd'
)
STORED AS AliOrc
LIFECYCLE 366;
