CREATE TABLE demo_dw.`dwd_trd_ord_line_df` (
  `ord_line_no` STRING COMMENT '订单子单号(item_no, 自然键)',
  `ord_no` STRING COMMENT '订单号(关联dwd_trd_ord_df)',
  `usr_id` BIGINT COMMENT '用户ID',
  `wh_id` BIGINT COMMENT '仓库ID(storage_no)',
  `cmpny_id` BIGINT COMMENT '采购公司ID',
  `usr_nm` STRING COMMENT '用户姓名(来自dim_usr_info_df)',
  `email` STRING COMMENT '用户邮箱',
  `wh_nm` STRING COMMENT '仓库名称(来自dim_wh_warehouse_df)',
  `item_id` BIGINT COMMENT '商品ID(goods_id)',
  `sku_id` BIGINT COMMENT 'SKU ID',
  `item_nm` STRING COMMENT '商品名称',
  `item_nm_cn` STRING COMMENT '商品中文名称',
  `item_attr` STRING COMMENT '商品属性',
  `item_attr_cn` STRING COMMENT '商品属性中文',
  `item_url` STRING COMMENT '商品链接',
  `item_img` STRING COMMENT '商品图片',
  `ord_line_stat` BIGINT COMMENT '子单状态编码: -1-待支付,0-待接单,2-待补款,5-已发货,8-已签收,10-已入库,11-作废,14-待确认,20-退货完成,22-已订购,23-处理中,24-取消订购,25-异常订单,28-出库中,30-寄送海外,31-已收到货,33-风控审核,39-拒签商品,50-强制完成,58-仓库处理中(共45种,详见ord_line_stat_nm)',
  `ord_line_stat_nm` STRING COMMENT '子单状态名称(ETL CASE WHEN 转换)',
  `cfm_stat` BIGINT COMMENT '待确认状态',
  `rtn_stat` BIGINT COMMENT '退换货状态',
  `sales_type_cd` BIGINT COMMENT '销售类型',
  `abn_type_cd` BIGINT COMMENT '异常类型',
  `cart_pur_type_cd` BIGINT COMMENT '购物车订购类型: 0-未订购, 1-已订购',
  `show_way_cd` BIGINT COMMENT '展示方式: 0-不展示, 1-我的仓库, 2-我的备货',
  `is_exprs_dlyd` BIGINT COMMENT '是否已快递发货: 0-否, 1-是',
  `is_need_cfm` BIGINT COMMENT '是否需要确认: 0-否, 1-是',
  `is_deferred` BIGINT COMMENT '是否延期处理: 0-否, 1-是',
  `ord_cnt` BIGINT COMMENT '商品数量(nums)',
  `prc` DECIMAL(18,4) COMMENT '商品单价(unit_price)',
  `pur_prc` DECIMAL(18,4) COMMENT '采购价格(write_price, 前台实际售价)',
  `vrtl_prc` DECIMAL(18,4) COMMENT '虚拟价格',
  `disc_amt` DECIMAL(18,4) COMMENT '优惠金额',
  `item_xtra_amt` DECIMAL(18,4) COMMENT '商品已补款金额(goods_fil)',
  `item_pend_xtra_amt` DECIMAL(18,4) COMMENT '商品待补款金额(goods_need_fil)',
  `booked_xtra_amt` DECIMAL(18,4) COMMENT '预定补款金额(booked_fil)',
  `rtn_amt` DECIMAL(18,4) COMMENT '商品退款金额(goods_return)',
  `rtn_fee` DECIMAL(18,4) COMMENT '退换货手续费(return_fee)',
  `back_post_amt` DECIMAL(18,4) COMMENT '寄回邮费(back_postage)',
  `ins_back_amt` DECIMAL(18,4) COMMENT '保险已赔金额(insurance_back)',
  `custom_fee` DECIMAL(18,4) COMMENT '定制服务费(fee_customize)',
  `wt` DECIMAL(18,4) COMMENT '商品重量(weight)',
  `pkg_no` STRING COMMENT '包裹单号(package_no, 防膨胀 ROW_NUMBER取最新)',
  `exprs_no` STRING COMMENT '快递单号(express_no)',
  `exprs_id` STRING COMMENT '快递公司编号(express_id)',
  `exprs_nm` STRING COMMENT '快递公司名称(express)',
  `pur_no` STRING COMMENT '采购单号(purchase_no)',
  `bin_no` STRING COMMENT '库位号(position_no)',
  `ml_lmt` STRING COMMENT '邮限(mail_limit)',
  `inv_id` STRING COMMENT '清单ID(inventory_id)',
  `ctgy_id` BIGINT COMMENT '商品分类ID(category_id)',
  `usr_cid` STRING COMMENT '用户分类ID(user_cid)',
  `pur_time` DATETIME COMMENT '订购时间(purchase_time)',
  `sign_time` DATETIME COMMENT '签收时间(signed_time)',
  `stor_out_time` DATETIME COMMENT '入库超期时间(storage_out_time)',
  `item_rmk` STRING COMMENT '商品备注(goods_comment)',
  `item_rmk_img` STRING COMMENT '备注图片(goods_extension)',
  `usr_rmk` STRING COMMENT '用户备注(comment)',
  `rmk_time` DATETIME COMMENT '备注添加时间(goods_comment_time)',
  `data_src` STRING COMMENT '数据来源: PREFERRED/AFFILIATES/OUTER',
  `vol_desc` STRING COMMENT '体积描述(长宽高)',
  `ds_ord_no` STRING COMMENT 'DS代发订单ID(plugin_order_id, 关联dwd_trd_ds_ord_header_df)',
  `ds_ord_line_no` STRING COMMENT 'DS代发订单行ID(plugin_line_id, 关联dwd_trd_ds_ord_line_df)',
  `bd_usr_nm` STRING COMMENT 'BD用户名(来自t_item_plugin及补充表，兜底主站指定用户BD映射)',
  `pur_sugg_prc` DECIMAL(18,4) COMMENT '采购建议价(purchase_suggestion_price)',
  `pur_sugg_post_prc` DECIMAL(18,4) COMMENT '采购建议邮费(purchase_suggestion_post_price)',
  `cmb_item_id` STRING COMMENT '组合商品ID(combine_goods_id)',
  `cmb_item_nm` STRING COMMENT '组合商品名称(combine_goods_name)',
  `cmb_item_attr` STRING COMMENT '组合商品属性(combine_goods_attribute)',
  `cmb_item_img` STRING COMMENT '组合商品图片(combine_goods_img)',
  `cmb_item_url` STRING COMMENT '组合商品URL(combine_goods_url)',
  `inner_sales_prc` DECIMAL(18,4) COMMENT '内部店铺售价(preferredAmount, 面向客户售价)',
  `inner_aff_prc` DECIMAL(18,4) COMMENT '内部联盟分销价(affiliatesAmount)',
  `inner_src_prc` DECIMAL(18,4) COMMENT '内部原始采购价(preferredAmountOrigin)',
  `plugin_cnt_json` STRING COMMENT '插件扩展JSON(content from t_item_plugin)',
  `xtn_json` STRING COMMENT '子单扩展字段JSON(extend_field)',
  `crt_time` DATETIME COMMENT '子单创建时间',
  `upd_time` DATETIME COMMENT '子单修改时间(来自t_order_item.update_time)'
)
COMMENT '交易域-网站原生订单子单日全量快照(4表整合+维度冗余)'
PARTITIONED BY (
  `ds` STRING NOT NULL COMMENT '分区日期 yyyyMMdd'
)
STORED AS AliOrc
LIFECYCLE 366;
