CREATE TABLE demo_dw.`dwd_trd_ds_ord_line_df` (
  `ord_line_no` BIGINT COMMENT 'DS订单行ID(draft_order_line主键)',
  `ord_no` BIGINT COMMENT 'DS订单ID(关联dwd_trd_ds_ord_header_df)',
  `draft_no` BIGINT COMMENT '草稿ID',
  `usr_id` BIGINT COMMENT '用户ID(下单用户)',
  `usr_nm` STRING COMMENT '用户姓名(来自dim_usr_info_df)',
  `email` STRING COMMENT '用户邮箱',
  `tb_shop_id` BIGINT COMMENT 'Tangbuy店铺ID',
  `tb_shop_url` STRING COMMENT 'Tangbuy店铺链接',
  `tb_shop_nm` STRING COMMENT 'Tangbuy店铺名称',
  `shop_pltf_cd` STRING COMMENT '店铺类型枚举: shopify / tiktok / woocommerce',
  `ord_line_stat` BIGINT COMMENT '订单行状态: 1-待处理, 2-待支付, 3-备货中, 4-待发货, 5-待送达, 6-已完结, 9-已取消, 10-已退款, 11-已失效',
  `pkg_no` STRING COMMENT '包裹单号(来自s_pack_item_ri, 防膨胀ROW_NUMBER取最新)',
  `tb_ord_line_no` STRING COMMENT 'Tangbuy商品编号(来自order_line_purchase.item_no)',
  `tb_item_type_cd` BIGINT COMMENT '商品类型: 1-普通商品, 2-组合商品',
  `data_src` STRING COMMENT '数据来源',
  `is_del` BIGINT COMMENT '是否删除: 0-否, 1-是',
  `tb_item_id` BIGINT COMMENT 'Tangbuy商品ID',
  `tb_sku_id` BIGINT COMMENT 'Tangbuy商品属性ID(SKU)',
  `tb_item_nm` STRING COMMENT 'Tangbuy商品名称',
  `tb_item_nm_cn` STRING COMMENT 'Tangbuy商品中文名称',
  `tb_item_attr` STRING COMMENT 'Tangbuy商品属性',
  `tb_item_attr_cn` STRING COMMENT 'Tangbuy商品属性中文',
  `tb_item_url` STRING COMMENT 'Tangbuy商品链接',
  `tb_item_img` STRING COMMENT 'Tangbuy商品图片',
  `prc` DECIMAL(18,4) COMMENT '商品单价',
  `pur_amt` DECIMAL(18,4) COMMENT '采购金额',
  `disc_amt` DECIMAL(18,4) COMMENT '优惠金额',
  `rtn_amt` DECIMAL(18,4) COMMENT '退款金额',
  `post_fee` DECIMAL(18,4) COMMENT '国内邮费',
  `splr_type_cd` STRING COMMENT '供应商类型',
  `pur_type_cd` BIGINT COMMENT '阶梯价类型: 0-不享受, 1-享受',
  `pur_rate` DECIMAL(18,4) COMMENT '组合商品计算比例(来自order_line_purchase)',
  `ord_cnt` BIGINT COMMENT '商品数量',
  `ref_cnt` BIGINT COMMENT '已退款数量',
  `crsh_cnt` BIGINT COMMENT '碰撞库存数量',
  `crsh_ref_cnt` BIGINT COMMENT '库存碰撞退款数量',
  `splr_item_id` STRING COMMENT '1688上游供应商商品ID(third_goods_id)',
  `splr_shop_id` STRING COMMENT '1688上游供应商店铺ID(third_shop_id)',
  `wt` DECIMAL(18,4) COMMENT '重量',
  `vol_desc` STRING COMMENT '体积描述(长宽高)',
  `rmk` STRING COMMENT '备注',
  `xtn_json` STRING COMMENT '扩展字段JSON(content)',
  `shop_id` STRING COMMENT '三方店铺ID(来自order_line_outer)',
  `shop_nm` STRING COMMENT '三方店铺名称(来自order_line_outer)',
  `ccy` STRING COMMENT '三方币种(来自order_line_outer)',
  `ord_amt` DECIMAL(18,4) COMMENT '三方订单行金额(来自order_line_outer)',
  `item_attr` STRING COMMENT '三方商品属性(来自order_line_outer)',
  `item_nm` STRING COMMENT '三方商品名称(来自order_line_outer)',
  `item_img` STRING COMMENT '三方商品图片(来自order_line_outer)',
  `item_cnt` BIGINT COMMENT '三方商品数量(来自order_line_outer)',
  `line_id` STRING COMMENT '三方行ID(来自order_line_outer)',
  `item_id` STRING COMMENT '三方商品ID(来自order_line_outer)',
  `sku_id` STRING COMMENT '三方SKU ID(来自order_line_outer)',
  `item_dim_id` BIGINT COMMENT '三方商品维度ID(来自dim_itm_out_item_df.out_item_dim_id)',
  `item_stat_cd` STRING COMMENT '三方商品状态(来自dim_itm_third_product_df): active-上架, draft-草稿, archived-归档下架',
  `sales_cnt_30d` BIGINT COMMENT '三方商品30日销量(来自dim_itm_third_product_df)',
  `crt_time` DATETIME COMMENT '订单行创建时间',
  `upd_time` DATETIME COMMENT '订单行修改时间',
  `rcd_crt_time` DATETIME COMMENT '外部订单行记录创建时间(t_order_line_outer.create_time)',
  `bd_usr_id` BIGINT COMMENT 'BD用户ID(来自t_item_plugin及补充表)',
  `bd_usr_nm` STRING COMMENT 'BD用户名(来自t_item_plugin及补充表)'
)
COMMENT '交易域-DS代发订单子单明细-日全量快照(3表整合+3维度冗余)'
PARTITIONED BY (
  `ds` STRING NOT NULL COMMENT '分区日期 yyyyMMdd'
)
STORED AS AliOrc
LIFECYCLE 366;
