CREATE TABLE demo_dw.`dwd_trd_ord_header_df` (
  `ord_no` STRING COMMENT '订单号(自然键)',
  `usr_id` BIGINT COMMENT '用户ID',
  `cmpny_id` BIGINT COMMENT '采购公司ID',
  `usr_nm` STRING COMMENT '用户姓名(来自dim_usr_info_df)',
  `usr_email` STRING COMMENT '用户邮箱(来自dim_usr_info_df)',
  `ord_stat` BIGINT COMMENT '订单状态: 0-待付款, 1-待接单, 2-处理中, 3-转单中, 4-取消订购, 5-邮费补款, 6-风控中, 7-撤单退款, 8-支付中, 9-已完成',
  `ord_type_cd` BIGINT COMMENT '订单类型: 0/1-普通接单池, 2/3-特殊接单池, 4-巴拿马接单池, 5-用户接单池, 6-用户转运, 7-1688API, 8-YINO接单池',
  `brand_stat` BIGINT COMMENT '品牌审核状态: 0-未审核, 1-审核通过',
  `pay_no` STRING COMMENT '支付单号',
  `slr_nm` STRING COMMENT '卖家名称',
  `buyer_nm` STRING COMMENT '采购员名称',
  `buyer_id` STRING COMMENT '采购员ID',
  `buyer_dept` STRING COMMENT '采购员部门',
  `dst_cntry` STRING COMMENT '配送目的地国家',
  `dst_cntry_id` BIGINT COMMENT '配送目的地国家ID',
  `shop_src` STRING COMMENT '店铺来源',
  `splr_shop_nm` STRING COMMENT '供应商店铺名称',
  `splr_shop_url` STRING COMMENT '供应商店铺URL',
  `splr_shop_id` STRING COMMENT '供应商店铺ID',
  `wh_id` BIGINT COMMENT '仓库ID(storage_no)',
  `wh_nm` STRING COMMENT '仓库名称(来自dim_wh_warehouse_df)',
  `lang` STRING COMMENT '下单语言',
  `ccy` STRING COMMENT '下单币种',
  `crt_time` DATETIME COMMENT '订单创建时间(下单时间)',
  `pend_time` DATETIME COMMENT '接单时间',
  `pay_time` DATETIME COMMENT '付款时间(来自订单主表)',
  `upd_time` DATETIME COMMENT '订单最后更新时间',
  `pay_rate` DECIMAL(18,4) COMMENT '支付汇率',
  `cmsn_rate` DECIMAL(18,4) COMMENT '店铺返利比例',
  `post_fee` DECIMAL(18,4) COMMENT '运费金额',
  `post_xtra_fee` DECIMAL(18,4) COMMENT '运费已补款金额',
  `post_pend_xtra_fee` DECIMAL(18,4) COMMENT '运费待补款金额',
  `post_ref_amt` DECIMAL(18,4) COMMENT '运费已退款金额',
  `srv_fee` DECIMAL(18,4) COMMENT '服务费',
  `tech_fee` DECIMAL(18,4) COMMENT '技术服务费',
  `tech_fee_ref_amt` DECIMAL(18,4) COMMENT '技术服务费退款金额',
  `itm_cnt` BIGINT COMMENT '商品总件数',
  `itm_sku_cnt` BIGINT COMMENT '商品SKU数(去重goods_id)',
  `itm_ord_amt` DECIMAL(18,4) COMMENT '商品订单金额合计(单价×数量汇总)',
  `itm_disc_amt` DECIMAL(18,4) COMMENT '商品优惠金额合计',
  `is_expd` BIGINT COMMENT '是否加急: 0-普通, 1-加急',
  `is_del` BIGINT COMMENT '是否删除: 0-否, 1-是',
  `usr_vip_lvl` BIGINT COMMENT '用户VIP等级',
  `sys_tag` STRING COMMENT '系统标记',
  `dev` STRING COMMENT '下单设备',
  `merge_item_json` STRING COMMENT '合并商品信息(JSON)',
  `acty_disc_json` STRING COMMENT '活动优惠信息(JSON)',
  `shop_id` STRING COMMENT '接单店铺ID（从xtn_json $.shopId解析）',
  `shop_url` STRING COMMENT '接单店铺链接（从xtn_json $.shopUrl解析）',
  `shop_nm` STRING COMMENT '接单店铺名称（从xtn_json $.shopName解析）',
  `inner_data_src` STRING COMMENT '接单数据来源（从xtn_json $.dataSource解析）',
  `xtn_json` STRING COMMENT '主单扩展字段(JSON)'
)
COMMENT '交易域-网站原生订单主单累积快照(4表整合+维度冗余)'
PARTITIONED BY (
  `ds` STRING NOT NULL COMMENT '分区日期 yyyyMMdd'
)
STORED AS AliOrc
LIFECYCLE 366;
