CREATE TABLE demo_dw.`dwd_trd_ds_ord_header_df` (
  `ord_no` BIGINT COMMENT '订单ID(草稿订单主键)',
  `usr_id` BIGINT COMMENT '用户ID(下单用户)',
  `usr_nm` STRING COMMENT '用户姓名(来自dim_usr_info_df)',
  `email` STRING COMMENT '用户邮箱',
  `ord_stat` BIGINT COMMENT '订单状态: 1-待处理, 2-待支付, 3-备货中, 4-待发货, 5-待送达, 6-已完结, 9-已取消, 10-已退款, 11-已失效',
  `ord_type_cd` BIGINT COMMENT '订单类型: 1-代发, 2-直购备货, 3-直购直发, 4-询盘备货, 5-询盘直发',
  `pay_no` STRING COMMENT '支付单号',
  `pay_time` DATETIME COMMENT '支付时间',
  `pur_amt` DECIMAL(18,4) COMMENT '采购金额',
  `ref_amt` DECIMAL(18,4) COMMENT '退款金额',
  `lang` STRING COMMENT '订单语言',
  `cntry` STRING COMMENT '国家(文本)',
  `cntry_id` BIGINT COMMENT '国家ID',
  `crsh` STRING COMMENT '碰撞信息',
  `cxl_rsn` STRING COMMENT '取消原因',
  `cxl_rsn_id` BIGINT COMMENT '取消原因ID',
  `exp_tm` BIGINT COMMENT '订单超时时间',
  `xtn_json` STRING COMMENT '扩展字段JSON(content)',
  `is_del` BIGINT COMMENT '是否删除: 0-否, 1-是',
  `out_ord_id` STRING COMMENT '三方订单ID(outer_order_id)',
  `out_ord_no` STRING COMMENT '三方订单号(outer_order_no)',
  `shop_id` STRING COMMENT '三方店铺ID(outer_shop_id)',
  `shop_nm` STRING COMMENT '三方店铺名称(outer_shop_name)',
  `shop_pltf_cd` STRING COMMENT '店铺类型枚举: shopify / tiktok / woocommerce',
  `ccy` STRING COMMENT '三方订单币种',
  `ord_amt` DECIMAL(18,4) COMMENT '三方订单总金额',
  `ord_rmk` STRING COMMENT '海外用户备注(outer_comment)',
  `cnt_json` STRING COMMENT '外部订单扩展JSON(content)',
  `out_crt_time` DATETIME COMMENT '外部订单创建时间(outer_create_time)',
  `out_upd_time` DATETIME COMMENT '外部订单更新时间(outer_update_time)',
  `rcv_nm` STRING COMMENT '收货人姓名',
  `rcv_fn` STRING COMMENT '收货人名',
  `rcv_ln` STRING COMMENT '收货人姓',
  `rcv_email` STRING COMMENT '收货人邮箱',
  `rcv_phn` STRING COMMENT '收货人电话',
  `rcv_cmpny` STRING COMMENT '收货人公司',
  `rcv_cntry` STRING COMMENT '收货国家',
  `rcv_cntry_id` BIGINT COMMENT '收货国家ID',
  `rcv_cntry_cd` STRING COMMENT '收货国家简码',
  `rcv_prov` STRING COMMENT '收货省份',
  `rcv_prov_cd` STRING COMMENT '收货省份编码',
  `rcv_city` STRING COMMENT '收货城市',
  `rcv_addr1` STRING COMMENT '收货地址行1',
  `rcv_addr2` STRING COMMENT '收货地址行2',
  `rcv_zip` STRING COMMENT '收货邮编',
  `rcv_lat` STRING COMMENT '收货纬度',
  `rcv_lng` STRING COMMENT '收货经度',
  `pkg_cnt` BIGINT COMMENT '包裹数量(来自pkg表COUNT)',
  `pkg_no_list` STRING COMMENT '包裹号列表(逗号分隔, WM_CONCAT聚合)',
  `pkg_latest_no` STRING COMMENT '最新包裹号',
  `pkg_latest_line_id` BIGINT COMMENT '最新包裹线路ID',
  `pkg_latest_line_nm` STRING COMMENT '最新包裹线路名称',
  `pkg_latest_dly_tm` STRING COMMENT '最新包裹预估时长',
  `pkg_latest_exprs_no` STRING COMMENT '最新包裹运单号',
  `pkg_latest_logis_nm` STRING COMMENT '最新包裹物流公司名称',
  `pkg_latest_logis_id` STRING COMMENT '最新包裹物流公司ID',
  `pkg_est_amt` DECIMAL(18,4) COMMENT '最新包裹预估费用',
  `pkg_actl_amt` DECIMAL(18,4) COMMENT '最新包裹实际费用',
  `pkg_est_wt` DECIMAL(18,4) COMMENT '最新包裹预估重量',
  `pkg_actl_wt` DECIMAL(18,4) COMMENT '最新包裹实际重量',
  `pkg_pend_amt` DECIMAL(18,4) COMMENT '最新包裹待补款金额',
  `pkg_payd_amt` DECIMAL(18,4) COMMENT '最新包裹已补款金额',
  `pkg_ref_amt` DECIMAL(18,4) COMMENT '最新包裹已退款金额',
  `pkg_rmk` STRING COMMENT '最新包裹备注',
  `pkg_cfg_json` STRING COMMENT '包裹选择配置JSON',
  `pkg_fee_json` STRING COMMENT '包裹费用JSON',
  `pkg_wrap_cd` STRING COMMENT '包裹包装类型: 极简包装/纸箱包装/未知包装(来自package_choosed_content.incrementList解析)',
  `crt_time` DATETIME COMMENT '订单创建时间',
  `upd_time` DATETIME COMMENT '订单更新时间',
  `rcd_crt_time` DATETIME COMMENT '外部订单记录创建时间(t_order_outer.create_time)'
)
COMMENT '交易域-DS代发订单累积快照事实表(4表整合+维度冗余)'
PARTITIONED BY (
  `ds` STRING NOT NULL COMMENT '分区日期 yyyyMMdd'
)
STORED AS AliOrc
LIFECYCLE 366;
