--@exclude_input=demo_dw.dwd_trd_order_operation_di
--MaxCompute SQL
--********************************************************************--
--author: 吴延俊
--create time: 2026-05-07 15:36:02
--********************************************************************--

WITH
today_raw AS (
    SELECT
        ord_line_no,
        crt_time,
        op_type_cn
    FROM demo_dw.dwd_trd_order_operation_di
    WHERE ds = '${bizdate}'
),

today_pivot AS (
    SELECT
        ord_line_no,
        MAX(CASE WHEN op_type_cn = '订单提交'     THEN crt_time END) AS ord_submit_time,
        MAX(CASE WHEN op_type_cn = '待支付'       THEN crt_time END) AS pend_pay_time,
        MAX(CASE WHEN op_type_cn = '预定购'       THEN crt_time END) AS pre_ord_time,
        MAX(CASE WHEN op_type_cn = '已订购'       THEN crt_time END) AS ord_time,
        MAX(CASE WHEN op_type_cn = '已支付'       THEN crt_time END) AS ord_pay_time,
        MAX(CASE WHEN op_type_cn = '处理中'       THEN crt_time END) AS proc_time,
        MAX(CASE WHEN op_type_cn = '修改分类'     THEN crt_time END) AS ctgy_upd_time,
        MAX(CASE WHEN op_type_cn = '仓库修改重量' THEN crt_time END) AS wh_wt_upd_time,
        MAX(CASE WHEN op_type_cn IN ('仓库已入库','系统入库') THEN crt_time END) AS wh_stock_in_time,
        MAX(CASE WHEN op_type_cn = '等待出库'     THEN crt_time END) AS pend_ob_time,
        MAX(CASE WHEN op_type_cn = '正在出库中'   THEN crt_time END) AS ob_ing_time,
        MAX(CASE WHEN op_type_cn = '出库打包完毕' THEN crt_time END) AS pkg_cmpl_time,
        MAX(CASE WHEN op_type_cn IN ('已发货','批量已发货') THEN crt_time END) AS snd_time,
        MAX(CASE WHEN op_type_cn = '已到货'       THEN crt_time END) AS arv_time,
        MAX(CASE WHEN op_type_cn = '已签收'       THEN crt_time END) AS sign_time,
        MAX(CASE WHEN op_type_cn = '已收到货'     THEN crt_time END) AS rcv_time,
        MAX(CASE WHEN op_type_cn = '取消订购'     THEN crt_time END) AS ord_cxl_time,
        MAX(CASE WHEN op_type_cn = '修改邮限'     THEN crt_time END) AS ml_lmt_upd_time,
        MAX(CASE WHEN op_type_cn = '修改库位号'   THEN crt_time END) AS bin_upd_time,
        MAX(CASE WHEN op_type_cn = '已寄送海外'     THEN crt_time END) AS snd_ovs_time,
        MAX(CASE WHEN op_type_cn = '撤销订单'         THEN crt_time END) AS ord_revoke_time,
        MAX(CASE WHEN op_type_cn = '巴拿马预定购'     THEN crt_time END) AS bnm_pre_ord_time,
        MAX(CASE WHEN op_type_cn = '巴拿马待支付'     THEN crt_time END) AS bnm_pend_pay_time,
        MAX(CASE WHEN op_type_cn = '预演出库'         THEN crt_time END) AS dry_ob_time,
        MAX(CASE WHEN op_type_cn = '待生成'           THEN crt_time END) AS pend_gen_time,
        MAX(CASE WHEN op_type_cn = '退款审核成功'     THEN crt_time END) AS ref_aud_pass_time,
        MAX(CASE WHEN op_type_cn = '取消包裹'         THEN crt_time END) AS pkg_cxl_time,
        MAX(CASE WHEN op_type_cn = '快递更新'         THEN crt_time END) AS exprs_upd_time,
        MAX(CASE WHEN op_type_cn = '申请退货'         THEN crt_time END) AS rtn_req_time,
        MAX(CASE WHEN op_type_cn = '打印快递单'       THEN crt_time END) AS exprs_lbl_print_time,
        MAX(CASE WHEN op_type_cn = '打印出库单'       THEN crt_time END) AS ob_bill_print_time,
        MAX(CASE WHEN op_type_cn = '退换货出库'       THEN crt_time END) AS rtn_exch_ob_time,
        MAX(CASE WHEN op_type_cn = '创建积分订单'     THEN crt_time END) AS pt_ord_crt_time,
        MAX(CASE WHEN op_type_cn = '退货完成'         THEN crt_time END) AS rtn_cmpl_time,
        MAX(CASE WHEN op_type_cn = '退货处理中'       THEN crt_time END) AS rtn_proc_time,
        MAX(CASE WHEN op_type_cn = '邮费补款'         THEN crt_time END) AS post_rchg_time,
        MAX(CASE WHEN op_type_cn = '采购员修改重量'   THEN crt_time END) AS pur_wt_upd_time,
        MAX(CASE WHEN op_type_cn = '订单退款'         THEN crt_time END) AS ord_ref_time,
        MAX(CASE WHEN op_type_cn = '邮费补款完成'     THEN crt_time END) AS post_rchg_cmpl_time,
        MAX(CASE WHEN op_type_cn = '待确认'           THEN crt_time END) AS pend_cfm_time,
        MAX(CASE WHEN op_type_cn = '已确认'           THEN crt_time END) AS cfm_time,
        MAX(CASE WHEN op_type_cn = '拆分商品'         THEN crt_time END) AS item_splt_time,
        MAX(CASE WHEN op_type_cn = '标签操作'         THEN crt_time END) AS tag_opt_time,
        MAX(CASE WHEN op_type_cn = '抓取修改商品属性' THEN crt_time END) AS item_attr_upd_time,
        MAX(CASE WHEN op_type_cn = '发送通知'         THEN crt_time END) AS ntfy_send_time,
        MAX(CASE WHEN op_type_cn = '交易关闭'         THEN crt_time END) AS txn_close_time,
        MAX(CASE WHEN op_type_cn = '通知撤回'         THEN crt_time END) AS ntfy_recall_time,
        MAX(CASE WHEN op_type_cn = '国内退包'         THEN crt_time END) AS dom_rtn_pkg_time,
        MAX(CASE WHEN op_type_cn = '风控审核'         THEN crt_time END) AS risk_aud_time,
        MAX(CASE WHEN op_type_cn = '分开发货'         THEN crt_time END) AS splt_snd_time,
        MAX(CASE WHEN op_type_cn = '巴拿马退货申请'   THEN crt_time END) AS bnm_rtn_req_time,
        MAX(CASE WHEN op_type_cn = '回到已签收'       THEN crt_time END) AS back_sign_time,
        MAX(CASE WHEN op_type_cn = '添加子订单'       THEN crt_time END) AS sub_ord_add_time,
        MAX(CASE WHEN op_type_cn = '临时区入库'       THEN crt_time END) AS tmp_wh_in_time,
        MAX(CASE WHEN op_type_cn = '临时区出库'       THEN crt_time END) AS tmp_wh_out_time,
        MAX(CASE WHEN op_type_cn = '换货处理中'         THEN crt_time END) AS exch_proc_time,
        MAX(CASE WHEN op_type_cn = '巴拿马待生成'       THEN crt_time END) AS bnm_pend_gen_time,
        MAX(CASE WHEN op_type_cn = '修改积分订单'       THEN crt_time END) AS pt_ord_upd_time,
        MAX(CASE WHEN op_type_cn = '巴拿马交易关闭'     THEN crt_time END) AS bnm_txn_close_time,
        MAX(CASE WHEN op_type_cn = '申请换货'           THEN crt_time END) AS exch_req_time,
        MAX(CASE WHEN op_type_cn = '退货取消'           THEN crt_time END) AS rtn_cxl_time,
        MAX(CASE WHEN op_type_cn = '强制完成'           THEN crt_time END) AS force_cmpl_time,
        MAX(CASE WHEN op_type_cn = '修改商品名称链接'   THEN crt_time END) AS item_nm_url_upd_time,
        MAX(CASE WHEN op_type_cn = '放弃商品'           THEN crt_time END) AS item_drop_time,
        MAX(CASE WHEN op_type_cn = '临时出库'           THEN crt_time END) AS tmp_ob_time,
        MAX(CASE WHEN op_type_cn = '商品补款'           THEN crt_time END) AS item_xtra_pay_time,
        MAX(CASE WHEN op_type_cn = '换货作废'           THEN crt_time END) AS exch_void_time,
        MAX(CASE WHEN op_type_cn = '国外退包'           THEN crt_time END) AS intl_rtn_pkg_time,
        MAX(CASE WHEN op_type_cn = '已订购申请退款'     THEN crt_time END) AS ord_ref_req_time,
        MAX(CASE WHEN op_type_cn = '商品补款完成'       THEN crt_time END) AS item_xtra_pay_cmpl_time,
        MAX(CASE WHEN op_type_cn = '取消风控审核'       THEN crt_time END) AS risk_aud_cxl_time,
        MAX(CASE WHEN op_type_cn = '取消冻结'           THEN crt_time END) AS frz_cxl_time,
        MAX(CASE WHEN op_type_cn = '换货取消'           THEN crt_time END) AS exch_cxl_time,
        MAX(CASE WHEN op_type_cn = '修改交易号'         THEN crt_time END) AS txn_id_upd_time,
        MAX(CASE WHEN op_type_cn = '回到处理中'         THEN crt_time END) AS back_proc_time,
        MAX(CASE WHEN op_type_cn = '已签收未发货'       THEN crt_time END) AS sign_not_snd_time,
        MAX(CASE WHEN op_type_cn = '销毁订单'           THEN crt_time END) AS ord_dstry_time,
        MAX(CASE WHEN op_type_cn = '采购提醒'           THEN crt_time END) AS pur_ntfy_time,
        MAX(CASE WHEN op_type_cn = '采购员已入库'       THEN crt_time END) AS pur_stk_in_time,
        MAX(CASE WHEN op_type_cn = '回到退货处理中'     THEN crt_time END) AS back_rtn_proc_time,
        MAX(CASE WHEN op_type_cn = '虚拟退货处理中'     THEN crt_time END) AS vrtl_rtn_proc_time,
        MAX(CASE WHEN op_type_cn = '平台商品售后'       THEN crt_time END) AS plat_item_after_sale_time,
        MAX(CASE WHEN op_type_cn = '修改状态'           THEN crt_time END) AS stat_upd_time,
        MAX(CASE WHEN op_type_cn = '延长存放时间'       THEN crt_time END) AS stor_ext_time,
        MAX(CASE WHEN op_type_cn = '领取积分订单'       THEN crt_time END) AS pt_ord_clct_time,
        MAX(CASE WHEN op_type_cn = '转移完成'           THEN crt_time END) AS tsfr_cmpl_time,
        MAX(CASE WHEN op_type_cn = '取消商品补款'       THEN crt_time END) AS item_xtra_pay_cxl_time,
        MAX(CASE WHEN op_type_cn = '退款审核失败'       THEN crt_time END) AS ref_aud_fail_time,
        MAX(CASE WHEN op_type_cn = '商品售后'           THEN crt_time END) AS item_after_sale_time,
        MAX(CASE WHEN op_type_cn = '取消邮费补款'       THEN crt_time END) AS post_rchg_cxl_time,
        MAX(CASE WHEN op_type_cn = '修改退换货类型'     THEN crt_time END) AS rtn_exch_type_upd_time,
        MAX(CASE WHEN op_type_cn = '作废订单'           THEN crt_time END) AS ord_void_time,
        MAX(CASE WHEN op_type_cn = '超期订单'           THEN crt_time END) AS overdue_ord_time,
        MAX(CASE WHEN op_type_cn = '仓库修改签收状态'   THEN crt_time END) AS wh_sign_stat_upd_time,
        MAX(CASE WHEN op_type_cn = '回到已发货'         THEN crt_time END) AS back_snd_time,
        MAX(CASE WHEN op_type_cn = '回到已订购'         THEN crt_time END) AS back_ord_time,
        MAX(CASE WHEN op_type_cn = '修改数量'           THEN crt_time END) AS qty_upd_time,
        MAX(CASE WHEN op_type_cn = '发起转单'           THEN crt_time END) AS tsfr_init_time,
        MAX(CASE WHEN op_type_cn = '转单成功'           THEN crt_time END) AS tsfr_succ_time,
        MAX(CASE WHEN op_type_cn = '退包作废'           THEN crt_time END) AS rtn_pkg_void_time,
        MAX(CASE WHEN op_type_cn = '预定补款完成'       THEN crt_time END) AS pre_pay_cmpl_time,
        MAX(CASE WHEN op_type_cn = '预定补款'           THEN crt_time END) AS pre_pay_time,
        MAX(CASE WHEN op_type_cn = '添加购物车未订购'   THEN crt_time END) AS cart_add_unord_time,
        MAX(CASE WHEN op_type_cn = '设置拒签'           THEN crt_time END) AS rjt_sign_time,
        MAX(CASE WHEN op_type_cn = '手动修改商品属性'   THEN crt_time END) AS manual_item_attr_upd_time,
        MAX(CASE WHEN op_type_cn = '回到换货处理中'     THEN crt_time END) AS back_exch_proc_time
    FROM today_raw
    GROUP BY ord_line_no
),

yesterday_snapshot AS (
    SELECT
        ord_line_no,
        ord_submit_time,
        pend_pay_time,
        pre_ord_time,
        ord_time,
        ord_pay_time,
        proc_time,
        ctgy_upd_time,
        wh_wt_upd_time,
        wh_stock_in_time,
        pend_ob_time,
        ob_ing_time,
        pkg_cmpl_time,
        snd_time,
        arv_time,
        sign_time,
        rcv_time,
        ord_cxl_time,
        ml_lmt_upd_time,
        bin_upd_time,
        snd_ovs_time,
        ord_revoke_time,
        bnm_pre_ord_time,
        bnm_pend_pay_time,
        dry_ob_time,
        pend_gen_time,
        ref_aud_pass_time,
        pkg_cxl_time,
        exprs_upd_time,
        rtn_req_time,
        exprs_lbl_print_time,
        ob_bill_print_time,
        rtn_exch_ob_time,
        pt_ord_crt_time,
        rtn_cmpl_time,
        rtn_proc_time,
        post_rchg_time,
        pur_wt_upd_time,
        ord_ref_time,
        post_rchg_cmpl_time,
        pend_cfm_time,
        cfm_time,
        item_splt_time,
        tag_opt_time,
        item_attr_upd_time,
        ntfy_send_time,
        txn_close_time,
        ntfy_recall_time,
        dom_rtn_pkg_time,
        risk_aud_time,
        splt_snd_time,
        bnm_rtn_req_time,
        back_sign_time,
        sub_ord_add_time,
        tmp_wh_in_time,
        tmp_wh_out_time,
        exch_proc_time,
        bnm_pend_gen_time,
        pt_ord_upd_time,
        bnm_txn_close_time,
        exch_req_time,
        rtn_cxl_time,
        force_cmpl_time,
        item_nm_url_upd_time,
        item_drop_time,
        tmp_ob_time,
        item_xtra_pay_time,
        exch_void_time,
        intl_rtn_pkg_time,
        ord_ref_req_time,
        item_xtra_pay_cmpl_time,
        risk_aud_cxl_time,
        frz_cxl_time,
        exch_cxl_time,
        txn_id_upd_time,
        back_proc_time,
        sign_not_snd_time,
        ord_dstry_time,
        pur_ntfy_time,
        pur_stk_in_time,
        back_rtn_proc_time,
        vrtl_rtn_proc_time,
        plat_item_after_sale_time,
        stat_upd_time,
        stor_ext_time,
        pt_ord_clct_time,
        tsfr_cmpl_time,
        item_xtra_pay_cxl_time,
        ref_aud_fail_time,
        item_after_sale_time,
        post_rchg_cxl_time,
        rtn_exch_type_upd_time,
        ord_void_time,
        overdue_ord_time,
        wh_sign_stat_upd_time,
        back_snd_time,
        back_ord_time,
        qty_upd_time,
        tsfr_init_time,
        tsfr_succ_time,
        rtn_pkg_void_time,
        pre_pay_cmpl_time,
        pre_pay_time,
        cart_add_unord_time,
        rjt_sign_time,
        manual_item_attr_upd_time,
        back_exch_proc_time
    FROM demo_dw.dws_trd_item_lifecycle_time_td
    WHERE ds = TO_CHAR(DATEADD(TO_DATE('${bizdate}', 'yyyymmdd'), -1, 'dd'), 'yyyymmdd')
)

INSERT OVERWRITE TABLE demo_dw.dws_trd_item_lifecycle_time_td PARTITION (ds = '${bizdate}')
SELECT
    NVL(t.ord_line_no, y.ord_line_no)                   AS ord_line_no,
    COALESCE(t.ord_submit_time,   y.ord_submit_time   ) AS ord_submit_time,
    COALESCE(t.pend_pay_time,     y.pend_pay_time     ) AS pend_pay_time,
    COALESCE(t.pre_ord_time,      y.pre_ord_time      ) AS pre_ord_time,
    COALESCE(t.ord_time,          y.ord_time          ) AS ord_time,
    COALESCE(t.ord_pay_time,      y.ord_pay_time      ) AS ord_pay_time,
    COALESCE(t.proc_time,         y.proc_time         ) AS proc_time,
    COALESCE(t.ctgy_upd_time,     y.ctgy_upd_time     ) AS ctgy_upd_time,
    COALESCE(t.wh_wt_upd_time,    y.wh_wt_upd_time    ) AS wh_wt_upd_time,
    COALESCE(t.wh_stock_in_time,  y.wh_stock_in_time  ) AS wh_stock_in_time,
    COALESCE(t.pend_ob_time,      y.pend_ob_time      ) AS pend_ob_time,
    COALESCE(t.ob_ing_time,       y.ob_ing_time       ) AS ob_ing_time,
    COALESCE(t.pkg_cmpl_time,     y.pkg_cmpl_time     ) AS pkg_cmpl_time,
    COALESCE(t.snd_time,          y.snd_time          ) AS snd_time,
    COALESCE(t.arv_time,          y.arv_time          ) AS arv_time,
    COALESCE(t.sign_time,         y.sign_time         ) AS sign_time,
    COALESCE(t.rcv_time,          y.rcv_time          ) AS rcv_time,
    COALESCE(t.ord_cxl_time,   y.ord_cxl_time   ) AS ord_cxl_time,
    COALESCE(t.ml_lmt_upd_time,   y.ml_lmt_upd_time   ) AS ml_lmt_upd_time,
    COALESCE(t.bin_upd_time,      y.bin_upd_time      ) AS bin_upd_time,
    COALESCE(t.snd_ovs_time,      y.snd_ovs_time      ) AS snd_ovs_time,
    COALESCE(t.ord_revoke_time,     y.ord_revoke_time     ) AS ord_revoke_time,
    COALESCE(t.bnm_pre_ord_time,    y.bnm_pre_ord_time    ) AS bnm_pre_ord_time,
    COALESCE(t.bnm_pend_pay_time,   y.bnm_pend_pay_time   ) AS bnm_pend_pay_time,
    COALESCE(t.dry_ob_time,         y.dry_ob_time         ) AS dry_ob_time,
    COALESCE(t.pend_gen_time,       y.pend_gen_time       ) AS pend_gen_time,
    COALESCE(t.ref_aud_pass_time,   y.ref_aud_pass_time   ) AS ref_aud_pass_time,
    COALESCE(t.pkg_cxl_time,        y.pkg_cxl_time        ) AS pkg_cxl_time,
    COALESCE(t.exprs_upd_time,      y.exprs_upd_time      ) AS exprs_upd_time,
    COALESCE(t.rtn_req_time,        y.rtn_req_time        ) AS rtn_req_time,
    COALESCE(t.exprs_lbl_print_time,y.exprs_lbl_print_time) AS exprs_lbl_print_time,
    COALESCE(t.ob_bill_print_time,  y.ob_bill_print_time  ) AS ob_bill_print_time,
    COALESCE(t.rtn_exch_ob_time,    y.rtn_exch_ob_time    ) AS rtn_exch_ob_time,
    COALESCE(t.pt_ord_crt_time,     y.pt_ord_crt_time     ) AS pt_ord_crt_time,
    COALESCE(t.rtn_cmpl_time,       y.rtn_cmpl_time       ) AS rtn_cmpl_time,
    COALESCE(t.rtn_proc_time,       y.rtn_proc_time       ) AS rtn_proc_time,
    COALESCE(t.post_rchg_time,      y.post_rchg_time      ) AS post_rchg_time,
    COALESCE(t.pur_wt_upd_time,     y.pur_wt_upd_time     ) AS pur_wt_upd_time,
    COALESCE(t.ord_ref_time,        y.ord_ref_time        ) AS ord_ref_time,
    COALESCE(t.post_rchg_cmpl_time, y.post_rchg_cmpl_time ) AS post_rchg_cmpl_time,
    COALESCE(t.pend_cfm_time,       y.pend_cfm_time       ) AS pend_cfm_time,
    COALESCE(t.cfm_time,            y.cfm_time            ) AS cfm_time,
    COALESCE(t.item_splt_time,      y.item_splt_time      ) AS item_splt_time,
    COALESCE(t.tag_opt_time,        y.tag_opt_time        ) AS tag_opt_time,
    COALESCE(t.item_attr_upd_time,  y.item_attr_upd_time  ) AS item_attr_upd_time,
    COALESCE(t.ntfy_send_time,      y.ntfy_send_time      ) AS ntfy_send_time,
    COALESCE(t.txn_close_time,      y.txn_close_time      ) AS txn_close_time,
    COALESCE(t.ntfy_recall_time,    y.ntfy_recall_time    ) AS ntfy_recall_time,
    COALESCE(t.dom_rtn_pkg_time,    y.dom_rtn_pkg_time    ) AS dom_rtn_pkg_time,
    COALESCE(t.risk_aud_time,       y.risk_aud_time       ) AS risk_aud_time,
    COALESCE(t.splt_snd_time,       y.splt_snd_time       ) AS splt_snd_time,
    COALESCE(t.bnm_rtn_req_time,    y.bnm_rtn_req_time    ) AS bnm_rtn_req_time,
    COALESCE(t.back_sign_time,      y.back_sign_time      ) AS back_sign_time,
    COALESCE(t.sub_ord_add_time,    y.sub_ord_add_time    ) AS sub_ord_add_time,
    COALESCE(t.tmp_wh_in_time,      y.tmp_wh_in_time      ) AS tmp_wh_in_time,
    COALESCE(t.tmp_wh_out_time,     y.tmp_wh_out_time     ) AS tmp_wh_out_time,
    COALESCE(t.exch_proc_time,          y.exch_proc_time          ) AS exch_proc_time,
    COALESCE(t.bnm_pend_gen_time,       y.bnm_pend_gen_time       ) AS bnm_pend_gen_time,
    COALESCE(t.pt_ord_upd_time,         y.pt_ord_upd_time         ) AS pt_ord_upd_time,
    COALESCE(t.bnm_txn_close_time,      y.bnm_txn_close_time      ) AS bnm_txn_close_time,
    COALESCE(t.exch_req_time,           y.exch_req_time           ) AS exch_req_time,
    COALESCE(t.rtn_cxl_time,            y.rtn_cxl_time            ) AS rtn_cxl_time,
    COALESCE(t.force_cmpl_time,         y.force_cmpl_time         ) AS force_cmpl_time,
    COALESCE(t.item_nm_url_upd_time,    y.item_nm_url_upd_time    ) AS item_nm_url_upd_time,
    COALESCE(t.item_drop_time,          y.item_drop_time          ) AS item_drop_time,
    COALESCE(t.tmp_ob_time,             y.tmp_ob_time             ) AS tmp_ob_time,
    COALESCE(t.item_xtra_pay_time,      y.item_xtra_pay_time      ) AS item_xtra_pay_time,
    COALESCE(t.exch_void_time,          y.exch_void_time          ) AS exch_void_time,
    COALESCE(t.intl_rtn_pkg_time,       y.intl_rtn_pkg_time       ) AS intl_rtn_pkg_time,
    COALESCE(t.ord_ref_req_time,        y.ord_ref_req_time        ) AS ord_ref_req_time,
    COALESCE(t.item_xtra_pay_cmpl_time, y.item_xtra_pay_cmpl_time ) AS item_xtra_pay_cmpl_time,
    COALESCE(t.risk_aud_cxl_time,       y.risk_aud_cxl_time       ) AS risk_aud_cxl_time,
    COALESCE(t.frz_cxl_time,            y.frz_cxl_time            ) AS frz_cxl_time,
    COALESCE(t.exch_cxl_time,           y.exch_cxl_time           ) AS exch_cxl_time,
    COALESCE(t.txn_id_upd_time,         y.txn_id_upd_time         ) AS txn_id_upd_time,
    COALESCE(t.back_proc_time,          y.back_proc_time          ) AS back_proc_time,
    COALESCE(t.sign_not_snd_time,       y.sign_not_snd_time       ) AS sign_not_snd_time,
    COALESCE(t.ord_dstry_time,          y.ord_dstry_time          ) AS ord_dstry_time,
    COALESCE(t.pur_ntfy_time,           y.pur_ntfy_time           ) AS pur_ntfy_time,
    COALESCE(t.pur_stk_in_time,         y.pur_stk_in_time         ) AS pur_stk_in_time,
    COALESCE(t.back_rtn_proc_time,      y.back_rtn_proc_time      ) AS back_rtn_proc_time,
    COALESCE(t.vrtl_rtn_proc_time,      y.vrtl_rtn_proc_time      ) AS vrtl_rtn_proc_time,
    COALESCE(t.plat_item_after_sale_time,y.plat_item_after_sale_time) AS plat_item_after_sale_time,
    COALESCE(t.stat_upd_time,           y.stat_upd_time           ) AS stat_upd_time,
    COALESCE(t.stor_ext_time,           y.stor_ext_time           ) AS stor_ext_time,
    COALESCE(t.pt_ord_clct_time,        y.pt_ord_clct_time        ) AS pt_ord_clct_time,
    COALESCE(t.tsfr_cmpl_time,          y.tsfr_cmpl_time          ) AS tsfr_cmpl_time,
    COALESCE(t.item_xtra_pay_cxl_time,  y.item_xtra_pay_cxl_time  ) AS item_xtra_pay_cxl_time,
    COALESCE(t.ref_aud_fail_time,       y.ref_aud_fail_time       ) AS ref_aud_fail_time,
    COALESCE(t.item_after_sale_time,    y.item_after_sale_time    ) AS item_after_sale_time,
    COALESCE(t.post_rchg_cxl_time,      y.post_rchg_cxl_time      ) AS post_rchg_cxl_time,
    COALESCE(t.rtn_exch_type_upd_time,  y.rtn_exch_type_upd_time  ) AS rtn_exch_type_upd_time,
    COALESCE(t.ord_void_time,           y.ord_void_time           ) AS ord_void_time,
    COALESCE(t.overdue_ord_time,        y.overdue_ord_time        ) AS overdue_ord_time,
    COALESCE(t.wh_sign_stat_upd_time,   y.wh_sign_stat_upd_time   ) AS wh_sign_stat_upd_time,
    COALESCE(t.back_snd_time,           y.back_snd_time           ) AS back_snd_time,
    COALESCE(t.back_ord_time,           y.back_ord_time           ) AS back_ord_time,
    COALESCE(t.qty_upd_time,            y.qty_upd_time            ) AS qty_upd_time,
    COALESCE(t.tsfr_init_time,          y.tsfr_init_time          ) AS tsfr_init_time,
    COALESCE(t.tsfr_succ_time,          y.tsfr_succ_time          ) AS tsfr_succ_time,
    COALESCE(t.rtn_pkg_void_time,       y.rtn_pkg_void_time       ) AS rtn_pkg_void_time,
    COALESCE(t.pre_pay_cmpl_time,       y.pre_pay_cmpl_time       ) AS pre_pay_cmpl_time,
    COALESCE(t.pre_pay_time,            y.pre_pay_time            ) AS pre_pay_time,
    COALESCE(t.cart_add_unord_time,     y.cart_add_unord_time     ) AS cart_add_unord_time,
    COALESCE(t.rjt_sign_time,           y.rjt_sign_time           ) AS rjt_sign_time,
    COALESCE(t.manual_item_attr_upd_time,y.manual_item_attr_upd_time) AS manual_item_attr_upd_time,
    COALESCE(t.back_exch_proc_time,     y.back_exch_proc_time     ) AS back_exch_proc_time
FROM today_pivot             t
FULL OUTER JOIN yesterday_snapshot y
ON t.ord_line_no = y.ord_line_no
;
