-- ============================================================
-- 数据域:   trd (交易域)
-- 业务过程: ord_opt (订单操作)
-- 表名:     dws_trd_item_lifecycle_time_1d
-- 表类型:   汇总事实表 (DWS Aggregate)
-- ETL方式:  首次全量初始化, 扫描 dwd 全量操作明细行转列
-- 调度变量: ${bizdate} 格式 yyyyMMdd (初始分区日期)
-- 说明:     本脚本仅在首次建表时执行一次, 日常调度使用 .etl.sql
-- ============================================================

INSERT OVERWRITE TABLE dws_trd_item_lifecycle_time_1d PARTITION (ds = '${bizdate}')
SELECT
    ord_line_no,
    MAX(CASE WHEN op_type_cn = '订单提交'     THEN create_time END) AS ord_submit_time,
    MAX(CASE WHEN op_type_cn = '待支付'       THEN create_time END) AS pend_pay_time,
    MAX(CASE WHEN op_type_cn = '预定购'       THEN create_time END) AS pre_ord_time,
    MAX(CASE WHEN op_type_cn = '已订购'       THEN create_time END) AS ord_time,
    MAX(CASE WHEN op_type_cn = '已支付'       THEN create_time END) AS ord_pay_time,
    MAX(CASE WHEN op_type_cn = '处理中'       THEN create_time END) AS proc_time,
    MAX(CASE WHEN op_type_cn = '修改分类'     THEN create_time END) AS ctgy_upd_time,
    MAX(CASE WHEN op_type_cn = '仓库修改重量' THEN create_time END) AS wh_wt_upd_time,
    MAX(CASE WHEN op_type_cn IN ('仓库已入库','系统入库') THEN create_time END) AS wh_stock_in_time,
    MAX(CASE WHEN op_type_cn = '等待出库'     THEN create_time END) AS pend_ob_time,
    MAX(CASE WHEN op_type_cn = '正在出库中'   THEN create_time END) AS ob_ing_time,
    MAX(CASE WHEN op_type_cn = '出库打包完毕' THEN create_time END) AS pkg_cmpl_time,
    MAX(CASE WHEN op_type_cn IN ('已发货','批量已发货') THEN create_time END) AS snd_time,
    MAX(CASE WHEN op_type_cn = '已到货'       THEN create_time END) AS arv_time,
    MAX(CASE WHEN op_type_cn = '已签收'       THEN create_time END) AS sign_time,
    MAX(CASE WHEN op_type_cn = '已收到货'     THEN create_time END) AS rcv_time,
    MAX(CASE WHEN op_type_cn = '取消订购'     THEN create_time END) AS ord_cxl_time,
    MAX(CASE WHEN op_type_cn = '修改邮限'     THEN create_time END) AS ml_lmt_upd_time,
    MAX(CASE WHEN op_type_cn = '修改库位号'   THEN create_time END) AS bin_upd_time,
    MAX(CASE WHEN op_type_cn = '已寄送海外'     THEN create_time END) AS snd_ovs_time,
    MAX(CASE WHEN op_type_cn = '撤销订单'         THEN create_time END) AS ord_revoke_time,
    MAX(CASE WHEN op_type_cn = '巴拿马预定购'     THEN create_time END) AS bnm_pre_ord_time,
    MAX(CASE WHEN op_type_cn = '巴拿马待支付'     THEN create_time END) AS bnm_pend_pay_time,
    MAX(CASE WHEN op_type_cn = '预演出库'         THEN create_time END) AS dry_ob_time,
    MAX(CASE WHEN op_type_cn = '待生成'           THEN create_time END) AS pend_gen_time,
    MAX(CASE WHEN op_type_cn = '退款审核成功'     THEN create_time END) AS ref_aud_pass_time,
    MAX(CASE WHEN op_type_cn = '取消包裹'         THEN create_time END) AS pkg_cxl_time,
    MAX(CASE WHEN op_type_cn = '快递更新'         THEN create_time END) AS exprs_upd_time,
    MAX(CASE WHEN op_type_cn = '申请退货'         THEN create_time END) AS rtn_req_time,
    MAX(CASE WHEN op_type_cn = '打印快递单'       THEN create_time END) AS exprs_lbl_print_time,
    MAX(CASE WHEN op_type_cn = '打印出库单'       THEN create_time END) AS ob_bill_print_time,
    MAX(CASE WHEN op_type_cn = '退换货出库'       THEN create_time END) AS rtn_exch_ob_time,
    MAX(CASE WHEN op_type_cn = '创建积分订单'     THEN create_time END) AS pt_ord_crt_time,
    MAX(CASE WHEN op_type_cn = '退货完成'         THEN create_time END) AS rtn_cmpl_time,
    MAX(CASE WHEN op_type_cn = '退货处理中'       THEN create_time END) AS rtn_proc_time,
    MAX(CASE WHEN op_type_cn = '邮费补款'         THEN create_time END) AS post_rchg_time,
    MAX(CASE WHEN op_type_cn = '采购员修改重量'   THEN create_time END) AS pur_wt_upd_time,
    MAX(CASE WHEN op_type_cn = '订单退款'         THEN create_time END) AS ord_ref_time,
    MAX(CASE WHEN op_type_cn = '邮费补款完成'     THEN create_time END) AS post_rchg_cmpl_time,
    MAX(CASE WHEN op_type_cn = '待确认'           THEN create_time END) AS pend_cfm_time,
    MAX(CASE WHEN op_type_cn = '已确认'           THEN create_time END) AS cfm_time,
    MAX(CASE WHEN op_type_cn = '拆分商品'         THEN create_time END) AS item_splt_time,
    MAX(CASE WHEN op_type_cn = '标签操作'         THEN create_time END) AS tag_opt_time,
    MAX(CASE WHEN op_type_cn = '抓取修改商品属性' THEN create_time END) AS item_attr_upd_time,
    MAX(CASE WHEN op_type_cn = '发送通知'         THEN create_time END) AS ntfy_send_time,
    MAX(CASE WHEN op_type_cn = '交易关闭'         THEN create_time END) AS txn_close_time,
    MAX(CASE WHEN op_type_cn = '通知撤回'         THEN create_time END) AS ntfy_recall_time,
    MAX(CASE WHEN op_type_cn = '国内退包'         THEN create_time END) AS dom_rtn_pkg_time,
    MAX(CASE WHEN op_type_cn = '风控审核'         THEN create_time END) AS risk_aud_time,
    MAX(CASE WHEN op_type_cn = '分开发货'         THEN create_time END) AS splt_snd_time,
    MAX(CASE WHEN op_type_cn = '巴拿马退货申请'   THEN create_time END) AS bnm_rtn_req_time,
    MAX(CASE WHEN op_type_cn = '回到已签收'       THEN create_time END) AS back_sign_time,
    MAX(CASE WHEN op_type_cn = '添加子订单'       THEN create_time END) AS sub_ord_add_time,
    MAX(CASE WHEN op_type_cn = '临时区入库'       THEN create_time END) AS tmp_wh_in_time,
    MAX(CASE WHEN op_type_cn = '临时区出库'       THEN create_time END) AS tmp_wh_out_time,
    MAX(CASE WHEN op_type_cn = '换货处理中'         THEN create_time END) AS exch_proc_time,
    MAX(CASE WHEN op_type_cn = '巴拿马待生成'       THEN create_time END) AS bnm_pend_gen_time,
    MAX(CASE WHEN op_type_cn = '修改积分订单'       THEN create_time END) AS pt_ord_upd_time,
    MAX(CASE WHEN op_type_cn = '巴拿马交易关闭'     THEN create_time END) AS bnm_txn_close_time,
    MAX(CASE WHEN op_type_cn = '申请换货'           THEN create_time END) AS exch_req_time,
    MAX(CASE WHEN op_type_cn = '退货取消'           THEN create_time END) AS rtn_cxl_time,
    MAX(CASE WHEN op_type_cn = '强制完成'           THEN create_time END) AS force_cmpl_time,
    MAX(CASE WHEN op_type_cn = '修改商品名称链接'   THEN create_time END) AS item_nm_url_upd_time,
    MAX(CASE WHEN op_type_cn = '放弃商品'           THEN create_time END) AS item_drop_time,
    MAX(CASE WHEN op_type_cn = '临时出库'           THEN create_time END) AS tmp_ob_time,
    MAX(CASE WHEN op_type_cn = '商品补款'           THEN create_time END) AS item_xtra_pay_time,
    MAX(CASE WHEN op_type_cn = '换货作废'           THEN create_time END) AS exch_void_time,
    MAX(CASE WHEN op_type_cn = '国外退包'           THEN create_time END) AS intl_rtn_pkg_time,
    MAX(CASE WHEN op_type_cn = '已订购申请退款'     THEN create_time END) AS ord_ref_req_time,
    MAX(CASE WHEN op_type_cn = '商品补款完成'       THEN create_time END) AS item_xtra_pay_cmpl_time,
    MAX(CASE WHEN op_type_cn = '取消风控审核'       THEN create_time END) AS risk_aud_cxl_time,
    MAX(CASE WHEN op_type_cn = '取消冻结'           THEN create_time END) AS frz_cxl_time,
    MAX(CASE WHEN op_type_cn = '换货取消'           THEN create_time END) AS exch_cxl_time,
    MAX(CASE WHEN op_type_cn = '修改交易号'         THEN create_time END) AS txn_id_upd_time,
    MAX(CASE WHEN op_type_cn = '回到处理中'         THEN create_time END) AS back_proc_time,
    MAX(CASE WHEN op_type_cn = '已签收未发货'       THEN create_time END) AS sign_not_snd_time,
    MAX(CASE WHEN op_type_cn = '销毁订单'           THEN create_time END) AS ord_dstry_time,
    MAX(CASE WHEN op_type_cn = '采购提醒'           THEN create_time END) AS pur_ntfy_time,
    MAX(CASE WHEN op_type_cn = '采购员已入库'       THEN create_time END) AS pur_stk_in_time,
    MAX(CASE WHEN op_type_cn = '回到退货处理中'     THEN create_time END) AS back_rtn_proc_time,
    MAX(CASE WHEN op_type_cn = '虚拟退货处理中'     THEN create_time END) AS vrtl_rtn_proc_time,
    MAX(CASE WHEN op_type_cn = '平台商品售后'       THEN create_time END) AS plat_item_after_sale_time,
    MAX(CASE WHEN op_type_cn = '修改状态'           THEN create_time END) AS stat_upd_time,
    MAX(CASE WHEN op_type_cn = '延长存放时间'       THEN create_time END) AS stor_ext_time,
    MAX(CASE WHEN op_type_cn = '领取积分订单'       THEN create_time END) AS pt_ord_clct_time,
    MAX(CASE WHEN op_type_cn = '转移完成'           THEN create_time END) AS tsfr_cmpl_time,
    MAX(CASE WHEN op_type_cn = '取消商品补款'       THEN create_time END) AS item_xtra_pay_cxl_time,
    MAX(CASE WHEN op_type_cn = '退款审核失败'       THEN create_time END) AS ref_aud_fail_time,
    MAX(CASE WHEN op_type_cn = '商品售后'           THEN create_time END) AS item_after_sale_time,
    MAX(CASE WHEN op_type_cn = '取消邮费补款'       THEN create_time END) AS post_rchg_cxl_time,
    MAX(CASE WHEN op_type_cn = '修改退换货类型'     THEN create_time END) AS rtn_exch_type_upd_time,
    MAX(CASE WHEN op_type_cn = '作废订单'           THEN create_time END) AS ord_void_time,
    MAX(CASE WHEN op_type_cn = '超期订单'           THEN create_time END) AS overdue_ord_time,
    MAX(CASE WHEN op_type_cn = '仓库修改签收状态'   THEN create_time END) AS wh_sign_stat_upd_time,
    MAX(CASE WHEN op_type_cn = '回到已发货'         THEN create_time END) AS back_snd_time,
    MAX(CASE WHEN op_type_cn = '回到已订购'         THEN create_time END) AS back_ord_time,
    MAX(CASE WHEN op_type_cn = '修改数量'           THEN create_time END) AS qty_upd_time,
    MAX(CASE WHEN op_type_cn = '发起转单'           THEN create_time END) AS tsfr_init_time,
    MAX(CASE WHEN op_type_cn = '转单成功'           THEN create_time END) AS tsfr_succ_time,
    MAX(CASE WHEN op_type_cn = '退包作废'           THEN create_time END) AS rtn_pkg_void_time,
    MAX(CASE WHEN op_type_cn = '预定补款完成'       THEN create_time END) AS pre_pay_cmpl_time,
    MAX(CASE WHEN op_type_cn = '预定补款'           THEN create_time END) AS pre_pay_time,
    MAX(CASE WHEN op_type_cn = '添加购物车未订购'   THEN create_time END) AS cart_add_unord_time,
    MAX(CASE WHEN op_type_cn = '设置拒签'           THEN create_time END) AS rjt_sign_time,
    MAX(CASE WHEN op_type_cn = '手动修改商品属性'   THEN create_time END) AS manual_item_attr_upd_time,
    MAX(CASE WHEN op_type_cn = '回到换货处理中'     THEN create_time END) AS back_exch_proc_time
FROM (
    SELECT ord_line_no, crt_time AS create_time, op_type_cn
    FROM dwd_trd_order_operation_di
) base
GROUP BY ord_line_no
;
