CREATE TABLE demo_dw.`dws_trd_ds_ord_line_td` (
  `ord_line_no` BIGINT COMMENT 'DS订单行ID(draft_order_line主键)，本表粒度',
  `ord_no` BIGINT COMMENT 'DS订单ID(关联dwd_trd_ds_ord_header_df)',
  `draft_no` BIGINT COMMENT 'DS草稿ID',
  `usr_id` BIGINT COMMENT '用户ID(下单用户)',
  `usr_nm` STRING COMMENT '用户姓名',
  `nick` STRING COMMENT '用户昵称',
  `email` STRING COMMENT '用户邮箱',
  `usr_cntry_cd` STRING COMMENT '用户注册国家简码',
  `usr_cntry_nm` STRING COMMENT '用户注册国家名称',
  `usr_lang` STRING COMMENT '用户语言偏好',
  `usr_stat` BIGINT COMMENT '用户账户状态: 0-无效, 1-有效',
  `is_usr_frz` BIGINT COMMENT '用户是否冻结: 0-否, 1-是',
  `is_usr_risk` BIGINT COMMENT '用户是否风险用户: 0-否, 1-是',
  `usr_lvl_id` BIGINT COMMENT '用户会员等级ID',
  `usr_lvl_nm` STRING COMMENT '用户会员等级名称',
  `usr_lvl` BIGINT COMMENT '用户会员等级值',
  `usr_crt_time` DATETIME COMMENT '用户注册时间',
  `shop_pltf_cd` STRING COMMENT '店铺平台编码: SHOPIFY/TIKTOK/WOOCOMMERCE',
  `shop_id` STRING COMMENT 'DS侧三方店铺ID',
  `shop_nm` STRING COMMENT 'DS侧三方店铺名称',
  `auth_rel_id` BIGINT COMMENT '店铺授权关系ID',
  `auth_stat` BIGINT COMMENT '店铺授权状态ID: 0-禁用, 1-启用, -1-未知',
  `auth_stat_nm` STRING COMMENT '店铺授权状态名称',
  `auth_shop_url` STRING COMMENT '授权店铺URL/域名',
  `auth_slr_nm` STRING COMMENT '授权店铺卖家名称',
  `auth_shop_rgn_cd` STRING COMMENT '授权店铺所在区域编码',
  `is_auth_shop_unreachable` BIGINT COMMENT '授权店铺是否无法访问: 0-否, 1-是',
  `auth_shop_unreachable_rsn` STRING COMMENT '授权店铺无法访问原因',
  `auth_shop_crt_time` DATETIME COMMENT '授权店铺创建时间',
  `auth_bd_usr_nm` STRING COMMENT '授权店铺当前关联BD名称列表',
  `is_auth_del` BIGINT COMMENT '授权店铺是否删除: 0-否, 1-是',
  `auth_crt_time` DATETIME COMMENT '授权创建时间',
  `auth_upd_time` DATETIME COMMENT '授权更新时间',
  `auth_revoke_time` DATETIME COMMENT '用户撤销店铺授权时间',
  `ord_stat` BIGINT COMMENT 'DS订单状态: 1-待处理, 2-待支付, 3-备货中, 4-待发货, 5-待送达, 6-已完结, 9-已取消, 10-已退款, 11-已失效',
  `ord_stat_nm` STRING COMMENT 'DS订单状态名称',
  `ord_type_cd` BIGINT COMMENT 'DS订单类型: 1-代发, 2-直购备货, 3-直购直发, 4-询盘备货, 5-询盘直发',
  `pay_no` STRING COMMENT 'DS订单支付单号',
  `pay_time` DATETIME COMMENT 'DS订单支付时间',
  `lang` STRING COMMENT 'DS订单语言',
  `cntry_id` BIGINT COMMENT 'DS订单国家ID',
  `cxl_rsn` STRING COMMENT 'DS订单取消原因',
  `cxl_rsn_id` BIGINT COMMENT 'DS订单取消原因ID',
  `is_ord_del` BIGINT COMMENT 'DS订单是否删除: 0-否, 1-是',
  `out_ord_id` STRING COMMENT '三方平台订单ID',
  `out_ord_no` STRING COMMENT '三方平台订单号',
  `ccy` STRING COMMENT '三方订单币种',
  `ord_amt` DECIMAL(18,4) COMMENT '三方订单总金额(原币)',
  `ord_amt_cny` DECIMAL(18,4) COMMENT '三方订单总金额(人民币，按ccy汇率折算)',
  `ord_rmk` STRING COMMENT '三方订单用户备注',
  `out_ord_crt_time` DATETIME COMMENT '三方订单创建时间',
  `out_ord_upd_time` DATETIME COMMENT '三方订单更新时间',
  `rcv_nm` STRING COMMENT '收货人姓名',
  `rcv_cntry_cd` STRING COMMENT '收货国家简码',
  `rcv_prov` STRING COMMENT '收货省份',
  `rcv_city` STRING COMMENT '收货城市',
  `ord_crt_time` DATETIME COMMENT 'DS订单创建时间',
  `ord_upd_time` DATETIME COMMENT 'DS订单更新时间',
  `ord_line_stat` BIGINT COMMENT 'DS订单行状态: 1-待处理, 2-待支付, 3-备货中, 4-待发货, 5-待送达, 6-已完结, 9-已取消, 10-已退款, 11-已失效',
  `is_line_del` BIGINT COMMENT 'DS订单行是否删除: 0-否, 1-是',
  `tb_shop_id` BIGINT COMMENT 'Tangbuy店铺ID',
  `tb_shop_nm` STRING COMMENT 'Tangbuy店铺名称',
  `tb_shop_url` STRING COMMENT 'Tangbuy店铺链接',
  `tb_ord_line_no` STRING COMMENT 'Tangbuy内部订单子单号(item_no，优先取最新内部子单，兜底DS采购补充item_no)',
  `tb_item_type_cd` BIGINT COMMENT 'Tangbuy商品类型: 1-普通商品, 2-组合商品',
  `data_src` STRING COMMENT '数据来源',
  `tb_item_id` BIGINT COMMENT 'Tangbuy商品ID',
  `tb_sku_id` BIGINT COMMENT 'Tangbuy SKU ID',
  `tb_item_nm_cn` STRING COMMENT 'Tangbuy商品中文名称',
  `tb_item_attr` STRING COMMENT 'Tangbuy商品属性',
  `tb_item_attr_cn` STRING COMMENT 'Tangbuy商品属性中文',
  `tb_item_url` STRING COMMENT 'Tangbuy商品链接',
  `item_prc` DECIMAL(18,4) COMMENT 'DS商品单价',
  `pur_amt` DECIMAL(18,4) COMMENT 'DS子单采购金额',
  `disc_amt` DECIMAL(18,4) COMMENT 'DS子单优惠金额',
  `rtn_amt` DECIMAL(18,4) COMMENT 'DS子单退款金额',
  `post_fee` DECIMAL(18,4) COMMENT 'DS子单国内邮费',
  `splr_type_cd` STRING COMMENT '供应商类型编码',
  `pur_type_cd` BIGINT COMMENT '阶梯价类型: 0-不享受, 1-享受',
  `pur_rate` DECIMAL(18,4) COMMENT '组合商品计算比例',
  `ord_cnt` BIGINT COMMENT 'DS子单商品数量',
  `ref_cnt` BIGINT COMMENT 'DS子单已退款数量',
  `crsh_cnt` BIGINT COMMENT 'DS子单碰撞库存数量',
  `crsh_ref_cnt` BIGINT COMMENT 'DS子单库存碰撞退款数量',
  `splr_item_id` STRING COMMENT '1688上游供应商商品ID',
  `splr_shop_id` STRING COMMENT '1688上游供应商店铺ID',
  `wt` DECIMAL(18,4) COMMENT 'DS子单商品重量',
  `vol_desc` STRING COMMENT 'DS子单体积描述(长宽高)',
  `rmk` STRING COMMENT 'DS子单备注',
  `pkg_no` STRING COMMENT '费用分摊包裹单号(优先沿用dws_trd_ds_ord_line_pkg_fee_td订单最新包裹口径)',
  `pkg_wrap_cd` STRING COMMENT '包裹包装类型: 极简包装/纸箱包装/未知包装',
  `fee_alloc_rate` DECIMAL(18,4) COMMENT '费用分摊比例(子单采购金额/包裹内子单采购金额合计)',
  `wt_alloc_rate` DECIMAL(18,4) COMMENT '重量分摊比例(子单重量/订单内子单重量合计)',
  `vol_alloc_rate` DECIMAL(18,4) COMMENT '体积分摊比例(子单体积/订单内子单体积合计)',
  `alloc_tot_pre_amt` DECIMAL(18,4) COMMENT '分摊预估总费用',
  `alloc_tot_actl_amt` DECIMAL(18,4) COMMENT '分摊实际总费用',
  `alloc_tech_srv_pre_fee` DECIMAL(18,4) COMMENT '分摊预估技术服务费',
  `alloc_tech_srv_actl_fee` DECIMAL(18,4) COMMENT '分摊实际技术服务费',
  `alloc_ins_amt` DECIMAL(18,4) COMMENT '分摊保险费',
  `alloc_diff_amt` DECIMAL(18,4) COMMENT '分摊费用差额',
  `alloc_succ_diff_amt` DECIMAL(18,4) COMMENT '分摊成功交易差额',
  `alloc_cpn_amt` DECIMAL(18,4) COMMENT '分摊优惠券金额',
  `alloc_disc_amt` DECIMAL(18,4) COMMENT '分摊折扣金额',
  `alloc_dep_amt` DECIMAL(18,4) COMMENT '分摊预存款',
  `alloc_actl_dep_amt` DECIMAL(18,4) COMMENT '分摊实际存款',
  `alloc_wt` DECIMAL(18,4) COMMENT '分摊重量(kg)，is_vol_wt_on=0时有效',
  `alloc_vol` DECIMAL(18,4) COMMENT '分摊体积(cm³)，is_vol_wt_on=1时有效',
  `is_gmv_abn` BIGINT COMMENT 'GMV异常标记: 1-异常需置0, 0-正常',
  `ord_gmv` DECIMAL(18,4) COMMENT '订单GMV(采购金额pur_amt, NVL兜底0, GREATEST取下限0, 异常状态置0)',
  `pkg_gmv` DECIMAL(18,4) COMMENT '包裹GMV(分摊预估总费用alloc_tot_pre_amt, NVL兜底0, GREATEST取下限0, 异常状态置0)',
  `tot_gmv` DECIMAL(18,4) COMMENT '订单行整体GMV(ord_gmv+pkg_gmv)',
  `pkg_stat` BIGINT COMMENT '包裹主状态',
  `pkg_stat_nm` STRING COMMENT '包裹主状态名称',
  `pkg_pay_stat` BIGINT COMMENT '包裹支付状态',
  `pkg_pay_stat_nm` STRING COMMENT '包裹支付状态名称',
  `pkg_bag_stat` BIGINT COMMENT '包裹退包状态',
  `pkg_bag_stat_nm` STRING COMMENT '包裹退包状态名称',
  `exprs_no` STRING COMMENT '包裹快递单号',
  `exprs_nm` STRING COMMENT '包裹快递公司名称',
  `pkg_line_nm` STRING COMMENT '包裹物流线路名称',
  `pkg_line_id` STRING COMMENT '包裹物流线路ID',
  `snd_area` STRING COMMENT '包裹发件地区',
  `pred_wt` DECIMAL(18,4) COMMENT '包裹预测重量',
  `actl_wt` DECIMAL(18,4) COMMENT '包裹实际重量',
  `pkg_actl_wt` DECIMAL(18,4) COMMENT '包裹打包后实际重量',
  `pkg_len` DECIMAL(18,4) COMMENT '包裹长度(cm)',
  `pkg_wid` DECIMAL(18,4) COMMENT '包裹宽度(cm)',
  `pkg_hgt` DECIMAL(18,4) COMMENT '包裹高度(cm)',
  `is_vol_wt_on` BIGINT COMMENT '包裹是否使用体积重: 0-否, 1-是',
  `pkg_snd_time` DATETIME COMMENT '包裹发货时间',
  `pkg_back_time` DATETIME COMMENT '包裹退回时间',
  `pkg_biz_rmk` STRING COMMENT '包裹业务备注',
  `item_attr` STRING COMMENT '三方商品属性',
  `item_nm` STRING COMMENT '三方商品名称',
  `item_img` STRING COMMENT '三方商品图片',
  `item_cnt` BIGINT COMMENT '三方商品数量',
  `out_ord_line_id` STRING COMMENT '三方平台订单行ID',
  `item_id` STRING COMMENT '三方商品ID',
  `sku_id` STRING COMMENT '三方SKU ID',
  `item_amt` DECIMAL(18,4) COMMENT '三方订单行金额(原币)',
  `item_amt_cny` DECIMAL(18,4) COMMENT '三方订单行金额(人民币，按ccy汇率折算)',
  `item_dim_id` BIGINT COMMENT '三方商品维度ID',
  `item_stat_cd` STRING COMMENT '三方商品状态编码: ACTIVE/DRAFT/ARCHIVED',
  `crt_time` DATETIME COMMENT 'DS订单行创建时间',
  `upd_time` DATETIME COMMENT 'DS订单行更新时间',
  `tb_ord_no` STRING COMMENT 'Tangbuy内部订单号(最新关联内部子单所属订单)',
  `tb_ord_stat` BIGINT COMMENT 'Tangbuy内部订单状态',
  `tb_ord_stat_nm` STRING COMMENT 'Tangbuy内部订单状态名称',
  `tb_ord_type_cd` BIGINT COMMENT 'Tangbuy内部订单类型编码',
  `tb_ord_line_stat` BIGINT COMMENT 'Tangbuy内部订单子单状态',
  `tb_ord_line_stat_nm` STRING COMMENT 'Tangbuy内部订单子单状态名称',
  `lvl1_ctgy_id` BIGINT COMMENT 'Tangbuy内部子单一级类目ID',
  `lvl1_ctgy_nm` STRING COMMENT 'Tangbuy内部子单一级类目名称',
  `lvl2_ctgy_id` BIGINT COMMENT 'Tangbuy内部子单二级类目ID',
  `lvl2_ctgy_nm` STRING COMMENT 'Tangbuy内部子单二级类目名称',
  `lvl3_ctgy_id` BIGINT COMMENT 'Tangbuy内部子单三级类目ID',
  `lvl3_ctgy_nm` STRING COMMENT 'Tangbuy内部子单三级类目名称',
  `lvl4_ctgy_id` BIGINT COMMENT 'Tangbuy内部子单四级类目ID',
  `lvl4_ctgy_nm` STRING COMMENT 'Tangbuy内部子单四级类目名称',
  `cstm_hs_cd` STRING COMMENT 'Tangbuy内部子单类目海关HS编码',
  `tb_wh_id` BIGINT COMMENT 'Tangbuy内部子单仓库ID',
  `tb_wh_nm` STRING COMMENT 'Tangbuy内部子单仓库名称',
  `tb_item_ord_amt` DECIMAL(18,4) COMMENT 'Tangbuy内部子单商品订单金额(采购价×数量)',
  `tb_item_xtra_amt` DECIMAL(18,4) COMMENT 'Tangbuy内部子单商品已补款金额',
  `tb_item_pend_xtra_amt` DECIMAL(18,4) COMMENT 'Tangbuy内部子单商品待补款金额',
  `tb_custom_fee` DECIMAL(18,4) COMMENT 'Tangbuy内部子单定制服务费',
  `tb_wt` DECIMAL(18,4) COMMENT 'Tangbuy内部子单商品重量',
  `tb_exprs_no` STRING COMMENT 'Tangbuy内部子单快递单号',
  `tb_exprs_nm` STRING COMMENT 'Tangbuy内部子单快递公司名称',
  `tb_pur_no` STRING COMMENT 'Tangbuy内部子单采购单号',
  `tb_line_crt_time` DATETIME COMMENT 'Tangbuy内部子单创建时间',
  `tb_line_upd_time` DATETIME COMMENT 'Tangbuy内部子单更新时间',
  `ord_submit_time` DATETIME COMMENT '履约节点-订单提交时间',
  `pend_pay_time` DATETIME COMMENT '履约节点-待支付时间',
  `ord_pay_time` DATETIME COMMENT '履约节点-已支付时间',
  `pur_time` DATETIME COMMENT '履约节点-已订购时间',
  `proc_time` DATETIME COMMENT '履约节点-处理中时间',
  `wh_stock_in_time` DATETIME COMMENT '履约节点-入库时间',
  `pend_ob_time` DATETIME COMMENT '履约节点-等待出库时间',
  `ob_ing_time` DATETIME COMMENT '履约节点-正在出库中时间',
  `pkg_cmpl_time` DATETIME COMMENT '履约节点-出库打包完毕时间',
  `snd_ovs_time` DATETIME COMMENT '履约节点-已寄送海外时间',
  `arv_time` DATETIME COMMENT '履约节点-已到货时间',
  `sign_time` DATETIME COMMENT '履约节点-已签收时间',
  `rcv_time` DATETIME COMMENT '履约节点-已收到货时间',
  `ord_cxl_time` DATETIME COMMENT '履约节点-取消订购时间',
  `rtn_req_time` DATETIME COMMENT '履约节点-申请退货时间',
  `rtn_cmpl_time` DATETIME COMMENT '履约节点-退货完成时间',
  `ord_ref_time` DATETIME COMMENT '履约节点-订单退款时间',
  `bd_usr_nm` STRING COMMENT '订单行BD用户名(来自dwd_trd_ds_ord_line_df.bd_usr_nm)'
)
COMMENT '交易域-DS订单行公共明细服务宽表-历史截至当日(组合DS订单/Tangbuy内部订单最新关联/用户/店铺授权/包裹费用分摊/物流信息)'
PARTITIONED BY (
  `ds` STRING NOT NULL COMMENT '分区日期 yyyyMMdd'
)
STORED AS AliOrc
LIFECYCLE 366;
