CREATE TABLE demo_dw.`dws_trd_ord_line_td` (
  `ord_line_no` STRING COMMENT 'Tangbuy内部订单子单号(item_no)，本表粒度',
  `ord_no` STRING COMMENT 'Tangbuy内部订单号',
  `usr_id` BIGINT COMMENT '用户ID',
  `usr_nm` STRING COMMENT '用户姓名',
  `email` STRING COMMENT '用户邮箱',
  `usr_cntry_cd` STRING COMMENT '用户注册国家简码',
  `usr_cntry_nm` STRING COMMENT '用户注册国家名称',
  `usr_lang` STRING COMMENT '用户语言偏好',
  `usr_stat` BIGINT COMMENT '用户账户状态: 0-无效, 1-有效',
  `is_usr_frz` BIGINT COMMENT '用户是否冻结: 0-否, 1-是',
  `is_usr_risk` BIGINT COMMENT '用户是否风险用户: 0-否, 1-是',
  `usr_lvl_id` BIGINT COMMENT '用户会员等级ID',
  `usr_lvl_nm` STRING COMMENT '用户会员等级名称',
  `usr_lvl` BIGINT COMMENT '用户会员等级值',
  `usr_crt_time` DATETIME COMMENT '用户注册时间',
  `cmpny_id` BIGINT COMMENT '采购公司ID',
  `ord_stat` BIGINT COMMENT 'Tangbuy内部订单状态: 0-待付款, 1-待接单, 2-处理中, 3-转单中, 4-取消订购, 5-邮费补款, 6-风控中, 7-撤单退款, 8-支付中, 9-已完成',
  `ord_stat_nm` STRING COMMENT 'Tangbuy内部订单状态名称',
  `ord_type_cd` BIGINT COMMENT 'Tangbuy内部订单类型编码',
  `item_aud_stat` BIGINT COMMENT '商品品牌审核状态: 0-未审核, 1-审核通过',
  `pay_no` STRING COMMENT 'Tangbuy内部订单支付单号',
  `slr_nm` STRING COMMENT '卖家名称',
  `pur_usr_nm` STRING COMMENT '采购员名称',
  `pur_usr_id` STRING COMMENT '采购员ID',
  `pur_usr_dept` STRING COMMENT '采购员部门',
  `rcv_cntry` STRING COMMENT '配送收货国家',
  `rcv_cntry_id` BIGINT COMMENT '配送收货国家ID',
  `shop_src` STRING COMMENT '接单店铺来源(优先取订单扩展字段dataSource，兜底订单店铺来源)',
  `shop_nm` STRING COMMENT '接单店铺名称(从订单扩展字段shopName解析)',
  `shop_url` STRING COMMENT '接单店铺URL(从订单扩展字段shopUrl解析)',
  `shop_id` STRING COMMENT '接单店铺ID(从订单扩展字段shopId解析)',
  `splr_shop_nm` STRING COMMENT '供应商店铺名称',
  `splr_shop_url` STRING COMMENT '供应商店铺URL',
  `splr_shop_id` STRING COMMENT '供应商店铺ID',
  `wh_id` BIGINT COMMENT '仓库ID',
  `wh_nm` STRING COMMENT '仓库名称',
  `lang` STRING COMMENT '下单语言',
  `ccy` STRING COMMENT '下单币种',
  `ord_pend_time` DATETIME COMMENT 'Tangbuy内部订单接单时间',
  `pay_time` DATETIME COMMENT 'Tangbuy内部订单付款时间',
  `ord_upd_time` DATETIME COMMENT 'Tangbuy内部订单最后更新时间',
  `is_expd` BIGINT COMMENT '是否加急: 0-否, 1-是',
  `is_ord_del` BIGINT COMMENT 'Tangbuy内部订单是否删除: 0-否, 1-是',
  `usr_vip_lvl` BIGINT COMMENT '订单侧用户VIP等级',
  `sys_tag` STRING COMMENT '系统标记',
  `dev` STRING COMMENT '下单设备',
  `merge_item_json` STRING COMMENT '合并商品信息JSON',
  `acty_disc_json` STRING COMMENT '活动优惠信息JSON',
  `ord_xtn_json` STRING COMMENT 'Tangbuy内部订单扩展字段JSON',
  `item_id` BIGINT COMMENT 'Tangbuy商品ID',
  `sku_id` BIGINT COMMENT 'Tangbuy SKU ID',
  `item_nm` STRING COMMENT 'Tangbuy商品名称',
  `item_nm_cn` STRING COMMENT 'Tangbuy商品中文名称',
  `item_attr` STRING COMMENT 'Tangbuy商品属性',
  `item_attr_cn` STRING COMMENT 'Tangbuy商品属性中文',
  `item_url` STRING COMMENT 'Tangbuy商品链接',
  `item_img` STRING COMMENT 'Tangbuy商品图片',
  `ord_line_stat` BIGINT COMMENT 'Tangbuy内部订单子单状态',
  `ord_line_stat_nm` STRING COMMENT 'Tangbuy内部订单子单状态名称',
  `cfm_stat` BIGINT COMMENT '待确认状态',
  `rtn_stat` BIGINT COMMENT '退换货状态',
  `sales_type_cd` BIGINT COMMENT '销售类型编码',
  `abn_type_cd` BIGINT COMMENT '异常类型编码',
  `cart_pur_type_cd` BIGINT COMMENT '购物车订购类型: 0-未订购, 1-已订购',
  `show_way_cd` BIGINT COMMENT '展示方式: 0-不展示, 1-我的仓库, 2-我的备货',
  `is_exprs_dlyd` BIGINT COMMENT '是否已快递发货: 0-否, 1-是',
  `is_need_cfm` BIGINT COMMENT '是否需要确认: 0-否, 1-是',
  `is_deferred` BIGINT COMMENT '是否延期处理: 0-否, 1-是',
  `ord_cnt` BIGINT COMMENT 'Tangbuy内部子单商品数量',
  `prc` DECIMAL(18,4) COMMENT 'Tangbuy内部子单商品单价',
  `pur_prc` DECIMAL(18,4) COMMENT 'Tangbuy内部子单采购价格',
  `item_ord_amt` DECIMAL(18,4) COMMENT 'Tangbuy内部子单商品订单金额(采购价×数量，原币)',
  `vrtl_prc` DECIMAL(18,4) COMMENT '虚拟价格',
  `disc_amt` DECIMAL(18,4) COMMENT 'Tangbuy内部子单优惠金额',
  `item_xtra_amt` DECIMAL(18,4) COMMENT 'Tangbuy内部子单商品已补款金额',
  `item_pend_xtra_amt` DECIMAL(18,4) COMMENT 'Tangbuy内部子单商品待补款金额',
  `booked_xtra_amt` DECIMAL(18,4) COMMENT 'Tangbuy内部子单预定补款金额',
  `rtn_amt` DECIMAL(18,4) COMMENT 'Tangbuy内部子单商品退款金额',
  `rtn_fee` DECIMAL(18,4) COMMENT 'Tangbuy内部子单退换货手续费',
  `back_post_amt` DECIMAL(18,4) COMMENT 'Tangbuy内部子单寄回邮费',
  `ins_back_amt` DECIMAL(18,4) COMMENT 'Tangbuy内部子单保险已赔金额',
  `custom_fee` DECIMAL(18,4) COMMENT 'Tangbuy内部子单定制服务费',
  `wt` DECIMAL(18,4) COMMENT 'Tangbuy内部子单商品重量',
  `vol_desc` STRING COMMENT 'Tangbuy内部子单体积描述(长宽高)',
  `line_vol` DECIMAL(18,4) COMMENT 'Tangbuy内部子单体积(cm³，由vol_desc解析)',
  `pkg_no` STRING COMMENT 'Tangbuy内部子单当前包裹单号',
  `exprs_no` STRING COMMENT 'Tangbuy内部子单快递单号',
  `exprs_id` STRING COMMENT 'Tangbuy内部子单快递公司编号',
  `exprs_nm` STRING COMMENT 'Tangbuy内部子单快递公司名称',
  `pur_no` STRING COMMENT 'Tangbuy内部子单采购单号',
  `bin_no` STRING COMMENT 'Tangbuy内部子单库位号',
  `ml_lmt` STRING COMMENT 'Tangbuy内部子单邮限',
  `inv_id` STRING COMMENT 'Tangbuy内部子单清单ID',
  `ctgy_id` BIGINT COMMENT 'Tangbuy内部子单商品分类ID',
  `lvl1_ctgy_id` BIGINT COMMENT 'Tangbuy内部子单一级类目ID',
  `lvl1_ctgy_nm` STRING COMMENT 'Tangbuy内部子单一级类目名称',
  `lvl2_ctgy_id` BIGINT COMMENT 'Tangbuy内部子单二级类目ID',
  `lvl2_ctgy_nm` STRING COMMENT 'Tangbuy内部子单二级类目名称',
  `lvl3_ctgy_id` BIGINT COMMENT 'Tangbuy内部子单三级类目ID',
  `lvl3_ctgy_nm` STRING COMMENT 'Tangbuy内部子单三级类目名称',
  `lvl4_ctgy_id` BIGINT COMMENT 'Tangbuy内部子单四级类目ID',
  `lvl4_ctgy_nm` STRING COMMENT 'Tangbuy内部子单四级类目名称',
  `dcl_cn_nm` STRING COMMENT 'Tangbuy内部子单类目申报中文名称',
  `dcl_en_nm` STRING COMMENT 'Tangbuy内部子单类目申报英文名称',
  `cstm_hs_cd` STRING COMMENT 'Tangbuy内部子单类目海关HS编码',
  `stor_out_time` DATETIME COMMENT 'Tangbuy内部子单入库超期时间',
  `item_rmk` STRING COMMENT 'Tangbuy内部子单商品备注',
  `item_rmk_img` STRING COMMENT 'Tangbuy内部子单备注图片',
  `usr_rmk` STRING COMMENT 'Tangbuy内部子单用户备注',
  `rmk_time` DATETIME COMMENT 'Tangbuy内部子单备注添加时间',
  `data_src` STRING COMMENT 'Tangbuy内部子单数据来源',
  `ds_ord_no` STRING COMMENT '关联DS订单ID',
  `ds_ord_line_no` STRING COMMENT '关联DS订单行ID',
  `bd_usr_nm` STRING COMMENT 'BD用户名(来自dwd_trd_ord_line_df.bd_usr_nm)',
  `pur_sugg_prc` DECIMAL(18,4) COMMENT '采购建议价',
  `pur_sugg_post_prc` DECIMAL(18,4) COMMENT '采购建议邮费',
  `cmb_item_id` STRING COMMENT '组合商品ID',
  `cmb_item_nm` STRING COMMENT '组合商品名称',
  `cmb_item_attr` STRING COMMENT '组合商品属性',
  `cmb_item_img` STRING COMMENT '组合商品图片',
  `cmb_item_url` STRING COMMENT '组合商品URL',
  `shop_prc` DECIMAL(18,4) COMMENT '已废弃: 大店加价价格(preferredAmount), 下游不要使用',
  `dist_prc` DECIMAL(18,4) COMMENT '已废弃: 大店联盟加价价格(affiliatesAmount), 下游不要使用',
  `orig_pur_prc` DECIMAL(18,4) COMMENT '已废弃: 大店原始加价价格(preferredAmountOrigin), 下游不要使用',
  `ds_ord_line_cnt_json` STRING COMMENT 'DS订单行扩展内容JSON',
  `line_xtn_json` STRING COMMENT 'Tangbuy内部子单扩展字段JSON',
  `line_crt_time` DATETIME COMMENT 'Tangbuy内部子单创建时间',
  `line_upd_time` DATETIME COMMENT 'Tangbuy内部子单更新时间',
  `ds_ord_stat` BIGINT COMMENT 'DS订单状态',
  `ds_ord_stat_nm` STRING COMMENT 'DS订单状态名称',
  `ds_ord_type_cd` BIGINT COMMENT 'DS订单类型编码',
  `ds_pay_no` STRING COMMENT 'DS订单支付单号',
  `ds_pay_time` DATETIME COMMENT 'DS订单支付时间',
  `ds_shop_pltf_cd` STRING COMMENT 'DS店铺平台编码',
  `ds_shop_id` STRING COMMENT 'DS三方店铺ID',
  `ds_shop_nm` STRING COMMENT 'DS三方店铺名称',
  `ds_out_ord_id` STRING COMMENT '三方平台订单ID',
  `ds_out_ord_no` STRING COMMENT '三方平台订单号',
  `ds_ccy` STRING COMMENT 'DS三方订单币种',
  `ds_ord_crt_time` DATETIME COMMENT 'DS订单创建时间',
  `ds_ord_upd_time` DATETIME COMMENT 'DS订单更新时间',
  `ds_ord_line_stat` BIGINT COMMENT 'DS订单行状态',
  `ds_is_line_del` BIGINT COMMENT 'DS订单行是否删除: 0-否, 1-是',
  `ds_item_amt` DECIMAL(18,4) COMMENT 'DS三方订单行金额(原币)',
  `ds_item_amt_cny` DECIMAL(18,4) COMMENT 'DS三方订单行金额(人民币，按ds_ccy汇率折算)',
  `is_gmv_abn` BIGINT COMMENT 'GMV异常标记: 1-异常需置0, 0-正常',
  `ord_gmv` DECIMAL(18,4) COMMENT '订单GMV(子单商品订单金额-优惠金额, NVL兜底0, GREATEST取下限0, 异常状态置0)',
  `pkg_gmv` DECIMAL(18,4) COMMENT '包裹GMV(分摊预估总费用alloc_tot_pre_amt, NVL兜底0, GREATEST取下限0, 异常状态置0)',
  `tot_gmv` DECIMAL(18,4) COMMENT '订单行整体GMV(ord_gmv+pkg_gmv)',
  `pkg_type_cd` STRING COMMENT '包裹类型编码',
  `pkg_cond_cd` STRING COMMENT '包裹打包条件编码',
  `fee_alloc_rate` DECIMAL(18,4) COMMENT '包裹费用分摊比例(内部子单商品订单金额/包裹内内部子单商品订单金额合计)',
  `wt_alloc_rate` DECIMAL(18,4) COMMENT '包裹重量分摊比例(内部子单重量/包裹内内部子单重量合计)',
  `vol_alloc_rate` DECIMAL(18,4) COMMENT '包裹体积分摊比例(内部子单体积/包裹内内部子单体积合计)',
  `alloc_tot_pre_amt` DECIMAL(18,4) COMMENT '分摊预估总费用',
  `alloc_tot_actl_amt` DECIMAL(18,4) COMMENT '分摊实际总费用',
  `alloc_tech_srv_pre_fee` DECIMAL(18,4) COMMENT '分摊预估技术服务费',
  `alloc_tech_srv_actl_fee` DECIMAL(18,4) COMMENT '分摊实际技术服务费',
  `alloc_ins_amt` DECIMAL(18,4) COMMENT '分摊保险费',
  `alloc_diff_amt` DECIMAL(18,4) COMMENT '分摊费用差额',
  `alloc_succ_diff_amt` DECIMAL(18,4) COMMENT '分摊成功交易差额',
  `alloc_cpn_amt` DECIMAL(18,4) COMMENT '分摊优惠券金额',
  `alloc_disc_amt` DECIMAL(18,4) COMMENT '分摊折扣金额',
  `alloc_dep_amt` DECIMAL(18,4) COMMENT '分摊预存款',
  `alloc_actl_dep_amt` DECIMAL(18,4) COMMENT '分摊实际存款',
  `alloc_wt` DECIMAL(18,4) COMMENT '分摊重量(kg)，is_vol_wt_on=0时有效',
  `alloc_vol` DECIMAL(18,4) COMMENT '分摊体积(cm³)，is_vol_wt_on=1时有效',
  `pkg_stat` BIGINT COMMENT '包裹主状态',
  `pkg_stat_nm` STRING COMMENT '包裹主状态名称',
  `pkg_pay_stat` BIGINT COMMENT '包裹支付状态',
  `pkg_pay_stat_nm` STRING COMMENT '包裹支付状态名称',
  `pkg_bag_stat` BIGINT COMMENT '包裹退包状态',
  `pkg_bag_stat_nm` STRING COMMENT '包裹退包状态名称',
  `pkg_exprs_no` STRING COMMENT '包裹快递单号',
  `pkg_exprs_nm` STRING COMMENT '包裹快递公司名称',
  `pkg_line_nm` STRING COMMENT '包裹物流线路名称',
  `pkg_line_id` STRING COMMENT '包裹物流线路ID',
  `snd_area` STRING COMMENT '包裹发件地区',
  `pkg_rcv_cntry_cd` STRING COMMENT '包裹收件国家ISO 3166-1 alpha-2代码',
  `pkg_rcv_cntry` STRING COMMENT '包裹收件国家英文标准名称',
  `pkg_rcv_cntry_cn` STRING COMMENT '包裹收件国家中文名称',
  `pkg_rcv_area` STRING COMMENT '包裹收件地区',
  `pkg_rcv_city` STRING COMMENT '包裹收件城市',
  `pred_wt` DECIMAL(18,4) COMMENT '包裹预测重量',
  `actl_wt` DECIMAL(18,4) COMMENT '包裹实际重量',
  `diff_wt` DECIMAL(18,4) COMMENT '包裹重量差异',
  `item_wt` DECIMAL(18,4) COMMENT '包裹商品总重量',
  `pkg_actl_wt` DECIMAL(18,4) COMMENT '包裹打包后实际重量',
  `pkg_len` DECIMAL(18,4) COMMENT '包裹长度(cm)',
  `pkg_wid` DECIMAL(18,4) COMMENT '包裹宽度(cm)',
  `pkg_hgt` DECIMAL(18,4) COMMENT '包裹高度(cm)',
  `is_vol_wt_on` BIGINT COMMENT '包裹是否使用体积重: 0-否, 1-是',
  `pkg_snd_time` DATETIME COMMENT '包裹发货时间',
  `pkg_back_time` DATETIME COMMENT '包裹退回时间',
  `pkg_dly_time` DATETIME COMMENT '包裹妥投时间',
  `pkg_biz_rmk` STRING COMMENT '包裹业务备注',
  `ord_submit_time` DATETIME COMMENT '履约节点-订单提交时间',
  `pend_pay_time` DATETIME COMMENT '履约节点-待支付时间',
  `ord_pay_time` DATETIME COMMENT '履约节点-已支付时间',
  `pur_time` DATETIME COMMENT '履约节点-已订购时间',
  `proc_time` DATETIME COMMENT '履约节点-处理中时间',
  `wh_stock_in_time` DATETIME COMMENT '履约节点-入库时间',
  `pend_ob_time` DATETIME COMMENT '履约节点-等待出库时间',
  `ob_ing_time` DATETIME COMMENT '履约节点-正在出库中时间',
  `pkg_cmpl_time` DATETIME COMMENT '履约节点-出库打包完毕时间',
  `snd_ovs_time` DATETIME COMMENT '履约节点-已寄送海外时间',
  `arv_time` DATETIME COMMENT '履约节点-已到货时间',
  `sign_time` DATETIME COMMENT '履约节点-已签收时间',
  `rcv_time` DATETIME COMMENT '履约节点-已收到货时间',
  `ord_cxl_time` DATETIME COMMENT '履约节点-取消订购时间',
  `rtn_req_time` DATETIME COMMENT '履约节点-申请退货时间',
  `rtn_cmpl_time` DATETIME COMMENT '履约节点-退货完成时间',
  `ord_ref_time` DATETIME COMMENT '履约节点-订单退款时间',
  `ord_crt_time` DATETIME COMMENT 'Tangbuy内部订单主单创建时间'
)
COMMENT '交易域-Tangbuy内部订单行公共明细服务宽表-历史截至当日(组合内部订单/DS关联/用户/类目/包裹费用分摊/物流信息)'
PARTITIONED BY (
  `ds` STRING NOT NULL COMMENT '分区日期 yyyyMMdd'
)
STORED AS AliOrc
LIFECYCLE 366;
