CREATE TABLE demo_dw.`dwd_wh_pkg_mgr_df` (
  `pkg_no` STRING COMMENT '包裹单号(package_no, 自然键)',
  `usr_id` BIGINT COMMENT '用户ID(user_id)',
  `wh_id` BIGINT COMMENT '仓库ID(storage_id)',
  `stor_ord_no` STRING COMMENT '入库单号(items_no, ODS原始字段)',
  `trade_no` STRING COMMENT '交易单号(trade_no)',
  `usr_nm` STRING COMMENT '用户姓名(来自dim_usr_info_df)',
  `email` STRING COMMENT '用户邮箱',
  `wh_nm` STRING COMMENT '仓库名称(来自dim_wh_warehouse_df)',
  `exprs_no` STRING COMMENT '快递单号(express_no)',
  `exprs_nm` STRING COMMENT '快递公司(logistic)',
  `line_nm` STRING COMMENT '物流线路名称(line)',
  `line_id` STRING COMMENT '物流线路ID(line_id)',
  `snd_area` STRING COMMENT '发件地区(send_area)',
  `carrier_id` STRING COMMENT '承运商ID(carrier_id)',
  `logistic_id` STRING COMMENT '物流商ID(logistic_id)',
  `rcv_first_nm` STRING COMMENT '收件人名(first_name)',
  `rcv_last_nm` STRING COMMENT '收件人姓(last_name)',
  `rcv_cntry_cd` STRING COMMENT '收件国家ISO 3166-1 alpha-2代码(匹配dim_comm_country_df.cntry_cd)',
  `rcv_cntry` STRING COMMENT '收件国家英文标准名称(匹配dim_comm_country_df.cntry_nm_en)',
  `rcv_cntry_cn` STRING COMMENT '收件国家中文名称(匹配dim_comm_country_df.cntry_nm)',
  `rcv_area` STRING COMMENT '收件地区(area)',
  `rcv_city` STRING COMMENT '收件城市(city)',
  `rcv_addr` STRING COMMENT '收件详细地址(address)',
  `rcv_zip` STRING COMMENT '收件邮编(post_code)',
  `rcv_phn` STRING COMMENT '收件电话(phone)',
  `pred_wt` DECIMAL(18,4) COMMENT '预测重量(predict_weight)',
  `actl_wt` DECIMAL(18,4) COMMENT '实际重量(act_weight)',
  `diff_wt` DECIMAL(18,4) COMMENT '重量差异(diff_weight)',
  `item_wt` DECIMAL(18,4) COMMENT '商品总重量(items_weight)',
  `pkg_actl_wt` DECIMAL(18,4) COMMENT '打包后实际重量(pack_weight_act)',
  `pkg_pre_actl_wt` DECIMAL(18,4) COMMENT '包裹预估实重(pre_weight_act)',
  `pkg_len` DECIMAL(18,4) COMMENT '包裹长度(lengths)',
  `pkg_wid` DECIMAL(18,4) COMMENT '包裹宽度(width)',
  `pkg_hgt` DECIMAL(18,4) COMMENT '包裹高度(height)',
  `pkg_vol` STRING COMMENT '包裹体积(pre_volume_act, from s_package_ri)',
  `dep_amt` DECIMAL(18,4) COMMENT '预存款(deposit)',
  `actl_dep_amt` DECIMAL(18,4) COMMENT '实际存款(act_deposit)',
  `tot_amt` DECIMAL(18,4) COMMENT '总金额(total_amount, 来自包裹主表)',
  `tot_pre_amt` DECIMAL(18,4) COMMENT '预估总费用(total_amount_pre)',
  `tot_actl_amt` DECIMAL(18,4) COMMENT '实际总费用(total_amount_act)',
  `tech_srv_pre_fee` DECIMAL(18,4) COMMENT '预估技术服务费(technical_service_fee_pre)',
  `tech_srv_actl_fee` DECIMAL(18,4) COMMENT '实际技术服务费(technical_service_fee_act)',
  `ins_amt` DECIMAL(18,4) COMMENT '保险费(insurance)',
  `ins_srv_fee` DECIMAL(18,4) COMMENT '投保费用(insurance_service)',
  `vat_amt` DECIMAL(18,4) COMMENT '增值税金额(value_added_tax)',
  `diff_amt` DECIMAL(18,4) COMMENT '费用差额(difference)',
  `succ_diff_amt` DECIMAL(18,4) COMMENT '成功交易差额(success_difference)',
  `cpn_amt` DECIMAL(18,4) COMMENT '优惠券金额(coupon)',
  `disc_amt` DECIMAL(18,4) COMMENT '折扣金额(discount)',
  `pkg_item_amt` DECIMAL(18,4) COMMENT '包裹商品实付金额(子单write_price*nums-discount_amount汇总)',
  `dcl_cn_nm_list` STRING COMMENT '申报商品中文名称列表(name_cn, 来自s_declare_fee_ri)',
  `dcl_en_nm_list` STRING COMMENT '申报商品英文名称列表(name_en, 来自s_declare_fee_ri)',
  `dcl_item_cnt` BIGINT COMMENT '申报商品数量合计(nums, 来自s_declare_fee_ri)',
  `dcl_amt` DECIMAL(18,4) COMMENT '申报金额合计(amount, 来自s_declare_fee_ri)',
  `item_cnt` BIGINT COMMENT '包裹内商品件数(来自s_pack_item_ri COUNT)',
  `exch_rate` DECIMAL(18,4) COMMENT '汇率(rate)',
  `ccy` STRING COMMENT '币种(currency)',
  `lang` STRING COMMENT '语言编码(lang): EN/ES/CN',
  `pltf_cd` STRING COMMENT '平台编码(plateform): APP/PC',
  `pkg_stat` BIGINT COMMENT '包裹主状态: 0-待处理,1-处理中,2-出库中,3-已出库,4-已打包,5-已称重,6-已打印运单号,7-已验证,8-已交接,9-已发货,20-确认收货(status, 映射来源dws_trd_ds_ord_line_td)',
  `pkg_stat_nm` STRING COMMENT '包裹主状态名称(status, 映射来源dws_trd_ds_ord_line_td)',
  `pay_stat` BIGINT COMMENT '支付状态: 0-待付款,1-处理中,2-已支付,3-已通知,4-已退款,5-失败,6-已取消(pay_status, 映射来源dws_trd_ds_ord_line_td)',
  `pay_stat_nm` STRING COMMENT '支付状态名称(pay_status, 映射来源dws_trd_ds_ord_line_td)',
  `bag_stat` BIGINT COMMENT '退包状态: 0-正常包裹,1-国内退包,2-国外退包,3-取消包裹,4-包裹待补款(bag_status, 映射来源dws_trd_ds_ord_line_td)',
  `bag_stat_nm` STRING COMMENT '退包状态名称(bag_status, 映射来源dws_trd_ds_ord_line_td)',
  `sys_stat` BIGINT COMMENT '系统审核状态(sys_status, 源表及公共字典未提供枚举标签, 当前值域0/1)',
  `artif_stat` BIGINT COMMENT '人工审核状态(artificial_status, 源表及公共字典未提供枚举标签, 当前值域0/1)',
  `risk_stat` BIGINT COMMENT '风控审核状态(risk_status, 源表及公共字典未提供枚举标签, 当前值域0/1)',
  `is_frz` BIGINT COMMENT '是否锁定/冻结: 0-否,1-是(lock_status)',
  `dcl_stat` BIGINT COMMENT '申报状态(declare_status, 源表及公共字典未提供枚举标签, 当前值域0/1)',
  `tax_type_cd` BIGINT COMMENT '缴税方式编码(tax_type): 0-收件人缴税,1-平台GST/VAT,2-个人GST/VAT,3-平台IOSS,4-个人IOSS,5-公司GST/VAT,6-物流商GST/VAT,7-物流商IOSS,8-免税',
  `tax_type_nm` STRING COMMENT '缴税方式名称(tax_type)',
  `is_pltf_ioss` BIGINT COMMENT '是否平台IOSS: 0-否,1-是(tax_type=3)',
  `logis_stat` BIGINT COMMENT '物流审核状态(logistics_status, 源表及公共字典未提供枚举标签, 当前值域1)',
  `cmpstn_stat` BIGINT COMMENT '理赔/赔付状态(compensation_status, 源注释为0-否/1-是, 但当前值域存在2, 含义待确认)',
  `is_after_sale` BIGINT COMMENT '是否售后: 0-否,1-是(after_sales_status)',
  `is_rtn` BIGINT COMMENT '是否退件: 0-否,1-是(return_status, from s_pack_info_ri)',
  `is_pend` BIGINT COMMENT '是否待处理: 0-否, 1-是(is_pending)',
  `is_del` BIGINT COMMENT '是否删除: 0-否, 1-是(is_delete)',
  `is_growth` BIGINT COMMENT '是否成长值包裹: 0-否, 1-是(is_growth)',
  `is_custom_aud` BIGINT COMMENT '是否定制物流审核: 0-否, 1-是(customized_audit)',
  `is_vol_wt_on` BIGINT COMMENT '是否使用体积重: 0-不使用, 1-使用(来自s_pack_weight_ri.use_volume_weight)',
  `custom_id` STRING COMMENT '定制物流ID(customized_id, 暂用全拼-无词根)',
  `risk_cd` STRING COMMENT '风控类型(risk_type)',
  `risk_lvl` STRING COMMENT '风控等级(risk)',
  `handle_cd` STRING COMMENT '处理方式(handle)',
  `pkg_type_cd` STRING COMMENT '包裹类型(package_type)',
  `spcl_stat_cd` STRING COMMENT '特殊状态(special_status)',
  `pkg_cond_cd` STRING COMMENT '打包条件(package_condition)',
  `pkg_usr` STRING COMMENT '打包人(create_by from s_pack_record_ri)',
  `crt_time` DATETIME COMMENT '创建时间(create_time)',
  `upd_time` DATETIME COMMENT '更新时间(update_time)',
  `pay_time` DATETIME COMMENT '支付时间(pay_time)',
  `exp_time` DATETIME COMMENT '过期时间(expire_time)',
  `snd_time` DATETIME COMMENT '发货时间(send_time)',
  `back_time` DATETIME COMMENT '退回时间(back_time)',
  `dly_time` DATETIME COMMENT '妥投时间(delivery_time, from s_pack_info_ri)',
  `cmpstn_time` DATETIME COMMENT '理赔时间(compensation_time)',
  `growth_time` DATETIME COMMENT '成长值时间(growth_time)',
  `biz_rmk` STRING COMMENT '业务备注(remark)',
  `bag_rmk` STRING COMMENT '装袋备注(bag_remark)',
  `exprs_stat` BIGINT COMMENT '快递轨迹状态(express_status, from logistics_track; 源表及公共字典未提供枚举标签, 当前值域0/1/10/20/30/31/35/40/50)',
  `trk_crt_time` DATETIME COMMENT '物流轨迹创建时间(create_time, from logistics_track)',
  `pick_time` DATETIME COMMENT '揽收时间(pick_time, from logistics_track)',
  `clr_time` DATETIME COMMENT '清关时间(clear_time, from logistics_track)',
  `trk_dly_time` DATETIME COMMENT '物流轨迹妥投时间(delivery_time, from logistics_track)',
  `last_trk_time` DATETIME COMMENT '最新轨迹时间(last_time, from logistics_track)',
  `dly_day_cnt` BIGINT COMMENT '妥投天数(delivery_days, from logistics_track)',
  `pxy_lbl_no` STRING COMMENT '代理面单号(track_no, from s_package_ri)'
)
COMMENT '仓储域-包裹全生命周期累积快照(包裹/费用/申报/轨迹整合+维度冗余)'
PARTITIONED BY (
  `ds` STRING NOT NULL COMMENT '分区日期 yyyyMMdd'
)
STORED AS AliOrc
LIFECYCLE 366;
