CREATE TABLE demo_dw.`dws_wh_pkg_mgr_td` (
  -- ============ 包裹标识 ============
  `pkg_no` STRING COMMENT '包裹单号(自然键, 本表粒度)',
  -- ============ 关联单号 ============
  `trade_no` STRING COMMENT '交易单号',
  `stor_ord_no` STRING COMMENT '入库单号',
  -- ============ 用户信息 ============
  `usr_id` BIGINT COMMENT '用户ID',
  `usr_nm` STRING COMMENT '用户姓名',
  `email` STRING COMMENT '用户邮箱',
  -- ============ 仓库信息 ============
  `wh_id` BIGINT COMMENT '仓库ID',
  `wh_nm` STRING COMMENT '仓库名称',
  -- ============ 收件信息 ============
  `rcv_first_nm` STRING COMMENT '收件人名',
  `rcv_last_nm` STRING COMMENT '收件人姓',
  `rcv_cntry_cd` STRING COMMENT '收件国家ISO 3166-1 alpha-2代码',
  `rcv_cntry` STRING COMMENT '收件国家英文标准名称',
  `rcv_cntry_cn` STRING COMMENT '收件国家中文名称',
  `rcv_area` STRING COMMENT '收件地区',
  `rcv_city` STRING COMMENT '收件城市',
  `rcv_zip` STRING COMMENT '收件邮编',
  `rcv_addr` STRING COMMENT '收件详细地址',
  `rcv_phn` STRING COMMENT '收件电话',
  -- ============ 物流线路与快递 ============
  `logistic_id` STRING COMMENT '物流商ID',
  `carrier_id` STRING COMMENT '承运商ID',
  `line_id` STRING COMMENT '物流线路ID',
  `line_nm` STRING COMMENT '物流线路名称',
  `exprs_nm` STRING COMMENT '快递公司',
  `exprs_no` STRING COMMENT '快递单号',
  `snd_area` STRING COMMENT '发件地区',
  -- ============ 重量与体积 ============
  `pred_wt` DECIMAL(18,4) COMMENT '预测重量',
  `actl_wt` DECIMAL(18,4) COMMENT '实际重量',
  `diff_wt` DECIMAL(18,4) COMMENT '重量差异',
  `item_wt` DECIMAL(18,4) COMMENT '商品总重量',
  `pkg_actl_wt` DECIMAL(18,4) COMMENT '打包后实际重量',
  `pkg_pre_actl_wt` DECIMAL(18,4) COMMENT '包裹预估实重',
  `is_vol_wt_on` BIGINT COMMENT '是否使用体积重: 0-不使用,1-使用',
  `pkg_len` DECIMAL(18,4) COMMENT '包裹长度',
  `pkg_wid` DECIMAL(18,4) COMMENT '包裹宽度',
  `pkg_hgt` DECIMAL(18,4) COMMENT '包裹高度',
  `pkg_vol` STRING COMMENT '包裹体积',
  -- ============ 金额与费用 ============
  `ccy` STRING COMMENT '币种',
  `exch_rate` DECIMAL(18,4) COMMENT '汇率',
  `dep_amt` DECIMAL(18,4) COMMENT '预存款',
  `actl_dep_amt` DECIMAL(18,4) COMMENT '实际存款',
  `tot_amt` DECIMAL(18,4) COMMENT '总金额',
  `tot_pre_amt` DECIMAL(18,4) COMMENT '预估总费用',
  `tot_actl_amt` DECIMAL(18,4) COMMENT '实际总费用',
  `tech_srv_pre_fee` DECIMAL(18,4) COMMENT '预估技术服务费',
  `tech_srv_actl_fee` DECIMAL(18,4) COMMENT '实际技术服务费',
  `ins_amt` DECIMAL(18,4) COMMENT '保险费',
  `ins_srv_fee` DECIMAL(18,4) COMMENT '投保费用',
  `vat_amt` DECIMAL(18,4) COMMENT '增值税金额',
  `diff_amt` DECIMAL(18,4) COMMENT '费用差额',
  `succ_diff_amt` DECIMAL(18,4) COMMENT '成功交易差额',
  `cpn_amt` DECIMAL(18,4) COMMENT '优惠券金额',
  `disc_amt` DECIMAL(18,4) COMMENT '折扣金额',
  `pkg_item_amt` DECIMAL(18,4) COMMENT '包裹商品实付金额',
  -- ============ 申报与税务 ============
  `dcl_cn_nm_list` STRING COMMENT '申报商品中文名称列表',
  `dcl_en_nm_list` STRING COMMENT '申报商品英文名称列表',
  `dcl_item_cnt` BIGINT COMMENT '申报商品数量合计',
  `dcl_amt` DECIMAL(18,4) COMMENT '申报金额合计',
  `tax_type_cd` BIGINT COMMENT '缴税方式编码: 0-收件人缴税,1-平台GST/VAT,2-个人GST/VAT,3-平台IOSS,4-个人IOSS,5-公司GST/VAT,6-物流商GST/VAT,7-物流商IOSS,8-免税',
  `tax_type_nm` STRING COMMENT '缴税方式名称',
  `is_pltf_ioss` BIGINT COMMENT '是否平台IOSS: 0-否,1-是',
  -- ============ 包裹状态 ============
  `pkg_stat` BIGINT COMMENT '包裹主状态: 0-待处理,1-处理中,2-出库中,3-已出库,4-已打包,5-已称重,6-已打印运单号,7-已验证,8-已交接,9-已发货,20-确认收货',
  `pkg_stat_nm` STRING COMMENT '包裹主状态名称',
  `pay_stat` BIGINT COMMENT '支付状态: 0-待付款,1-处理中,2-已支付,3-已通知,4-已退款,5-失败,6-已取消',
  `pay_stat_nm` STRING COMMENT '支付状态名称',
  `bag_stat` BIGINT COMMENT '退包状态: 0-正常包裹,1-国内退包,2-国外退包,3-取消包裹,4-包裹待补款',
  `bag_stat_nm` STRING COMMENT '退包状态名称',
  `exprs_stat` BIGINT COMMENT '快递轨迹状态',
  -- ============ 审核与标记 ============
  `sys_stat` BIGINT COMMENT '系统审核状态',
  `artif_stat` BIGINT COMMENT '人工审核状态',
  `risk_stat` BIGINT COMMENT '风控审核状态',
  `is_frz` BIGINT COMMENT '是否锁定/冻结: 0-否,1-是',
  `dcl_stat` BIGINT COMMENT '申报状态',
  `logis_stat` BIGINT COMMENT '物流审核状态',
  `cmpstn_stat` BIGINT COMMENT '理赔/赔付状态',
  `is_after_sale` BIGINT COMMENT '是否售后: 0-否,1-是',
  `is_rtn` BIGINT COMMENT '是否退件: 0-否,1-是',
  `is_pend` BIGINT COMMENT '是否待处理: 0-否,1-是',
  `is_del` BIGINT COMMENT '是否删除: 0-否,1-是',
  `is_growth` BIGINT COMMENT '是否成长值包裹: 0-否,1-是',
  `is_custom_aud` BIGINT COMMENT '是否定制物流审核: 0-否,1-是',
  -- ============ 包裹属性与标签 ============
  `pkg_type_cd` STRING COMMENT '包裹类型',
  `pkg_cond_cd` STRING COMMENT '打包条件',
  `spcl_stat_cd` STRING COMMENT '特殊状态',
  `risk_cd` STRING COMMENT '风控类型',
  `risk_lvl` STRING COMMENT '风控等级',
  `handle_cd` STRING COMMENT '处理方式',
  `custom_id` STRING COMMENT '定制物流ID',
  `pkg_usr` STRING COMMENT '打包人',
  `item_cnt` BIGINT COMMENT '包裹内商品件数',
  `lang` STRING COMMENT '语言编码',
  `pltf_cd` STRING COMMENT '平台编码',
  -- ============ 业务备注 ============
  `biz_rmk` STRING COMMENT '业务备注',
  `bag_rmk` STRING COMMENT '装袋备注',
  -- ============ 时间里程碑（业务顺序） ============
  `crt_time` DATETIME COMMENT '包裹创建时间',
  `ord_crt_time` DATETIME COMMENT '订单下单时间(来自dwd_trd_ord_header_df, 多订单取最晚)',
  `ord_pay_time` DATETIME COMMENT '订单支付时间(来自dwd_trd_ord_header_df, 多订单取最晚)',
  `pay_time` DATETIME COMMENT '包裹支付时间(来自包裹系统)',
  `upd_time` DATETIME COMMENT '最后更新时间',
  `snd_time` DATETIME COMMENT '发货时间',
  `trk_crt_time` DATETIME COMMENT '物流轨迹创建时间',
  `pick_time` DATETIME COMMENT '揽收时间',
  `exp_time` DATETIME COMMENT '过期时间',
  `clr_time` DATETIME COMMENT '清关时间',
  `trk_dly_time` DATETIME COMMENT '物流轨迹妥投时间',
  `last_trk_time` DATETIME COMMENT '最新轨迹时间',
  `dly_time` DATETIME COMMENT '妥投时间',
  `dly_day_cnt` BIGINT COMMENT '妥投天数',
  `back_time` DATETIME COMMENT '退回时间',
  `cmpstn_time` DATETIME COMMENT '理赔时间',
  `growth_time` DATETIME COMMENT '成长值时间',
  -- ============ 追加字段 ============
  `pxy_lbl_no` STRING COMMENT '代理面单号(来自dwd_wh_pkg_mgr_df.pxy_lbl_no, 源字段track_no)'
)
COMMENT '仓储域-包裹管理宽表-历史截至当日(透传包裹/申报/税务/轨迹信息并补充订单下单/支付时间, 每日全量重算)'
PARTITIONED BY (
  `ds` STRING NOT NULL COMMENT '分区日期 yyyyMMdd'
)
STORED AS AliOrc
LIFECYCLE 366;
