CREATE TABLE demo_dw.`dim_itm_item_df` (
  `item_id` BIGINT COMMENT '商品ID（自然键）',
  `item_nm` STRING COMMENT '商品名称',
  `item_nm_cn` STRING COMMENT '商品中文名称/多语言名称',
  `imgs` STRING COMMENT '商品主图',
  `item_mv` STRING COMMENT '商品MV视频',
  `detail_url` STRING COMMENT '商品详情链接(来自product_item.detail_url)',
  `detail` STRING COMMENT '商品详情描述(来自product_details.detail)',
  `spec_param` STRING COMMENT '规格参数(来自product_details.spec_param)',
  `item_attr_json` STRING COMMENT '商品属性JSON(来自product_details.product_attributes_json)',
  `item_desc` STRING COMMENT '商品详情富文本(来自product_details.description)',
  `lang_pack_json` STRING COMMENT '多语言包JSON(来自product_details.lang_pack_map_json)',
  `risk_info_json` STRING COMMENT '风险信息JSON(来自product_details.risk_info_json)',
  `detail_rmk` STRING COMMENT '详情备注(来自product_details.remark)',
  `detail_rmk_imgs` STRING COMMENT '详情备注图片(来自product_details.remark_images)',
  `min_prc` DECIMAL(18,4) COMMENT '价格',
  `max_prc` DECIMAL(18,4) COMMENT '最高价格',
  `crossed_prc` DECIMAL(18,4) COMMENT '最低划线价',
  `post_fee` DECIMAL(18,4) COMMENT '国内运费',
  `freight_type_cd` STRING COMMENT '运费类型编码',
  `cmsn_prc_cfg_json` STRING COMMENT '佣金规则配置JSON',
  `item_stat` BIGINT COMMENT '商品状态: 0-上架, 1-下架, 11-商家商品已提交, 12-商家商品审批被驳回, 13-商家商品平台拉黑, 14-商家商品回收站, -1-未知',
  `pltf_stat` BIGINT COMMENT '商品平台状态: 0-正常, 1-下架, 2-违禁商品, 3-侵权商品, 4-违规店铺, 5-销量不达标, 6-劣质商品, 10-一级风控, 11-二级风控, 20-审核提交, 21-审核驳回',
  `is_sold_out` BIGINT COMMENT '是否售罄: 0-否, 1-是',
  `is_hot` BIGINT COMMENT '是否爆品: 0-否, 1-是',
  `is_tiered_prc` BIGINT COMMENT '是否有阶梯价: 0-否, 1-是',
  `is_accept_splr_chg` BIGINT COMMENT '是否接受原商品变更: 0-否, 1-是',
  `item_assemble_stat` BIGINT COMMENT '聚合状态: 0-上架(正常), 5-链接变更, 10-商品下架, -1-未知',
  `invalid_time` DATETIME COMMENT '失效时间',
  `data_src` STRING COMMENT '数据来源',
  `splr_type_cd` STRING COMMENT '供应商平台类型编码',
  `splr_item_key` STRING COMMENT '供应商商品KEY',
  `splr_item_info_id` BIGINT COMMENT '供应商商品信息表ID',
  `splr_nm` STRING COMMENT '供应商店铺名称',
  `splr_shop_url` STRING COMMENT '供应商店铺URL',
  `splr_logo` STRING COMMENT '供应商店铺Logo',
  `splr_item_id` STRING COMMENT '供应商商品ID',
  `splr_detail_url` STRING COMMENT '供应商直达链接',
  `splr_prc` DECIMAL(18,4) COMMENT '供应商采集价格',
  `splr_max_prc` DECIMAL(18,4) COMMENT '供应商采集最高价格',
  `adjust_cnt` BIGINT COMMENT '净重尺校准次数',
  `ctgy_id` BIGINT COMMENT '所属类目ID',
  `ctgy_nm` STRING COMMENT '所属类目名称',
  `ctgy_nm_lang_json` STRING COMMENT '类目名称多语言JSON',
  `ctgy_path` STRING COMMENT '类目路径(祖先链)',
  `ctgy_lvl` BIGINT COMMENT '类目层级',
  `parent_ctgy_id` BIGINT COMMENT '父类目ID',
  `ctgy_is_leaf` BIGINT COMMENT '是否叶子类目: 0-否, 1-是',
  `ctgy_logo` STRING COMMENT '类目图标',
  `ctgy_sort_order` BIGINT COMMENT '类目排序号',
  `ctgy_stat` BIGINT COMMENT '类目状态: 0-禁用, 1-启用',
  `shop_id` BIGINT COMMENT '关联店铺ID',
  `is_del` BIGINT COMMENT '是否删除: 0-否, 1-是',
  `ver` BIGINT COMMENT '版本号',
  `crt_time` DATETIME COMMENT '创建时间',
  `upd_time` DATETIME COMMENT '更新时间',
  `is_tb` BIGINT COMMENT '是否平台优选商品: 0-否, 1-是',
  `tb_lvl` STRING COMMENT '平台优选商品等级(S/A/B/C/未知)',
  `tb_ownr_nm` STRING COMMENT '平台优选原创人员名',
  `tb_choice_score` BIGINT COMMENT '平台优选评分',
  `tb_incr_rate` DECIMAL(18,6) COMMENT '平台优选加价比例',
  `tb_suit_cntry` STRING COMMENT '平台优选适合国家',
  `tb_ownr_time` DATETIME COMMENT '平台优选原创时间',
  `tb_sgst_sale_prc_json` STRING COMMENT '平台优选建议零售价JSON'
)
COMMENT '商品SPU维度表-日全量快照(合并类目/详情/供应商, 全量映射)'
PARTITIONED BY (
  `ds` STRING NOT NULL COMMENT '分区日期 yyyyMMdd'
)
STORED AS AliOrc
LIFECYCLE 36500;
