CREATE TABLE demo_dw.`dim_usr_info_df` (
  `usr_id` BIGINT COMMENT '用户ID（自然键）',
  `usr_nm` STRING COMMENT '用户真实姓名',
  `nick` STRING COMMENT '用户昵称',
  `email` STRING COMMENT '邮箱',
  `phn` STRING COMMENT '手机号',
  `gndr_cd` STRING COMMENT '性别枚举: 男 / 女 / 未知',
  `dob` STRING COMMENT '出生日期',
  `lang` STRING COMMENT '语言偏好',
  `img` STRING COMMENT '头像URL',
  `cntry_cd` STRING COMMENT '注册国家简码',
  `cntry_nm` STRING COMMENT '国家名称中文（来自ods_manual_country_code）',
  `prov` STRING COMMENT '省份',
  `city` STRING COMMENT '城市',
  `reg_ip` STRING COMMENT '注册IP',
  `usr_stat` BIGINT COMMENT '账户状态: 0-无效, 1-有效 (已做CASE WHEN纠偏: ODS 0=有效→1 有效)',
  `is_frz` BIGINT COMMENT '是否锁定: 0-否, 1-是',
  `is_risk` BIGINT COMMENT '是否风险用户: 0-否, 1-是',
  `is_del` BIGINT COMMENT '是否删除: 0-否, 1-是',
  `is_pay_free_on` BIGINT COMMENT '是否开启免密支付: 0-否, 1-是',
  `pay_free_limit` DECIMAL(18,4) COMMENT '免密支付限额',
  `rjt_cnt` BIGINT COMMENT '累计拒付次数',
  `lvl_id` BIGINT COMMENT '会员等级ID（关联member_config.id）',
  `lvl_nm` STRING COMMENT '会员等级名称',
  `lvl` BIGINT COMMENT '会员等级值',
  `growth` BIGINT COMMENT '当前成长值',
  `integral` BIGINT COMMENT '当前积分',
  `cpn_cnt` BIGINT COMMENT '等级权益-优惠券数量',
  `fare_rate` DECIMAL(18,4) COMMENT '等级权益-运费折扣比例',
  `rtn_exch_cnt` BIGINT COMMENT '等级权益-每月免费退换货次数',
  `fine_photo_cnt` BIGINT COMMENT '等级权益-免费精细拍照次数',
  `fast_rsp_cnt` BIGINT COMMENT '等级权益-极速响应免费次数',
  `prvw_pkg_cnt` BIGINT COMMENT '等级权益-预演包装免费次数',
  `append_disc` DECIMAL(18,4) COMMENT '等级权益-增值服务优惠折扣',
  `ins_disc` DECIMAL(18,4) COMMENT '等级权益-保险优惠折扣',
  `bal_amt` DECIMAL(18,4) COMMENT '钱包余额',
  `rebate_amt` DECIMAL(18,4) COMMENT '佣金返利余额',
  `frz_amt` DECIMAL(18,4) COMMENT '冻结金额',
  `ovdft_amt` DECIMAL(18,4) COMMENT '欠款金额',
  `wh_id` BIGINT COMMENT '归属仓库ID',
  `app_os` STRING COMMENT '设备系统(iOS/Android)',
  `pltf_cd` STRING COMMENT '平台类型编码',
  `reg_pltf_cd` STRING COMMENT '注册平台编码(Google/Facebook等), 邮箱直注用户为email',
  `fcm_tkn` STRING COMMENT 'Firebase推送Token',
  `app_ver` STRING COMMENT 'APP版本号',
  `is_agreement_read` BIGINT COMMENT '是否已阅读隐私协议: 0-否, 1-是',
  `is_declaration_ok` BIGINT COMMENT '平台优化声明函状态: 0-未确认, 1-已确认',
  `is_wm_on` BIGINT COMMENT '是否使用水印: 0-否, 1-是',
  `wm_nm` STRING COMMENT '水印标题',
  `wm_bg_img` STRING COMMENT '水印背景图',
  `usr_tag_list` STRING COMMENT '用户标签列表(逗号分隔)',
  `rcmd_pmt_id` BIGINT COMMENT '上级推广者ID(来自cps.promoter_id)',
  `shr_cd` STRING COMMENT '注册分享码(来自cps.share_code)',
  `rcmd_cmsn_amt` DECIMAL(18,4) COMMENT '推荐佣金金额(来自cps.commission_amount)',
  `wa_dial_cd` STRING COMMENT 'WhatsApp区号(来自活动表,ROW_NUMBER取最新)',
  `wa_phn` STRING COMMENT 'WhatsApp号码(来自活动表,ROW_NUMBER取最新)',
  `fb_id` STRING COMMENT 'Facebook ID(来自活动表,ROW_NUMBER取最新)',
  `ig_id` STRING COMMENT 'Instagram ID(来自活动表,ROW_NUMBER取最新)',
  `is_ebk_usr` BIGINT COMMENT '是否Supabase Auth用户: 0-否, 1-是（通过email与ods_supabase_auth_users_df关联）',
  `crt_time` DATETIME COMMENT '注册时间',
  `upd_time` DATETIME COMMENT '最后更新时间'
)
COMMENT '用户维度表-日全量快照(合并会员等级/设备/水印/标签)'
PARTITIONED BY (
  `ds` STRING NOT NULL COMMENT '分区日期 yyyyMMdd'
)
STORED AS AliOrc
LIFECYCLE 36500;
