CREATE TABLE demo_dw.`dwd_usr_behav_event_di` (
  `event_date` STRING COMMENT '事件日期 yyyyMMdd',
  `event_time` DATETIME COMMENT '事件时间(UTC+8)',
  `event_hour` BIGINT COMMENT '事件小时(0-23, UTC+8)',
  `event_nm` STRING COMMENT '事件名称(如 screen_view/purchase)',
  `src_cd` STRING COMMENT '数据来源: firebase',
  `usr_pseudo_id` STRING COMMENT '用户匿名标识(设备级)',
  `usr_id` STRING COMMENT '用户ID(登录后)',
  `pltf_cd` STRING COMMENT '平台: IOS/ANDROID/WEB',
  `stream_id` BIGINT COMMENT '数据流ID',
   stream_nm string comment '数据流名称',
  `event_usd_amt` DOUBLE COMMENT '事件价值(USD)',
  `sess_id` BIGINT COMMENT 'GA会话ID(来自event_params.ga_session_id)',
  `sess_seq_no` BIGINT COMMENT 'GA会话序号(来自event_params.ga_session_number)',
  `is_sess_engaged` BIGINT COMMENT '会话是否参与互动(1是0否, 来自event_params.session_engaged)',
  `is_engaged_sess_event` BIGINT COMMENT '是否参与会话事件(1是0否, 来自event_params.engaged_session_event)',
  `engage_time_ms` BIGINT COMMENT '参与时长毫秒(来自event_params.engagement_time_msec)',
  `entrance_cnt` BIGINT COMMENT '入口次数(来自event_params.entrances)',
  `batch_page_id` STRING COMMENT '批次页面ID(来自event_params.batch_page_id)',
  `batch_seq_no` BIGINT COMMENT '批次序号(来自event_params.batch_ordering_id)',
  `event_orig_cd` STRING COMMENT '事件原始来源编码(来自event_params.origin)',
  `view_nm` STRING COMMENT '视图名称(WEB: page_title, 移动端: firebase_screen)',
  `view_url` STRING COMMENT '视图URL(WEB: page_location)',
  `page_path` STRING COMMENT '页面路径(来自event_params.page_path)',
  `page_referrer_url` STRING COMMENT '页面引荐URL(来自event_params.page_referrer)',
  `view_class` STRING COMMENT '视图类名(移动端: firebase_screen_class)',
  `view_id` STRING COMMENT '视图ID(移动端: firebase_screen_id)',
  `prev_view_nm` STRING COMMENT '前一视图名称(移动端: firebase_previous_screen)',
  `prev_view_class` STRING COMMENT '前一视图类名(移动端: firebase_previous_class)',
  `prev_view_id` STRING COMMENT '前一视图ID(移动端: firebase_previous_id)',
  `firebase_event_orig_cd` STRING COMMENT 'Firebase事件原始来源编码(来自event_params.firebase_event_origin)',
  `event_src_nm` STRING COMMENT '事件参数来源(来自event_params.source)',
  `event_medium` STRING COMMENT '事件参数媒介(来自event_params.medium)',
  `event_acty_nm` STRING COMMENT '事件参数活动名称(来自event_params.campaign)',
  `gclid` STRING COMMENT 'Google点击ID(来自event_params.gclid)',
  `gad_src_cd` STRING COMMENT 'Google广告来源编码(来自event_params.gad_source)',
  `gad_acty_id` STRING COMMENT 'Google广告活动ID(来自event_params.gad_campaignid)',
  `attr_usr_id` STRING COMMENT '用户属性中的用户ID(来自user_properties.user_id)',
  `shr_cd` STRING COMMENT '分享码(来自user_properties.share_code)',
  `first_open_time` DATETIME COMMENT '首次打开时间(来自user_properties.first_open_time)',
  `attr_sess_id` BIGINT COMMENT '用户属性中的GA会话ID(来自user_properties.ga_session_id)',
  `attr_sess_seq_no` BIGINT COMMENT '用户属性中的GA会话序号(来自user_properties.ga_session_number)',
  `attr_usr_id_set_time` DATETIME COMMENT '用户ID属性设置时间(来自user_properties.user_id.set_timestamp_micros)',
  `shr_cd_set_time` DATETIME COMMENT '分享码属性设置时间(来自user_properties.share_code.set_timestamp_micros)',
  `first_open_set_time` DATETIME COMMENT '首次打开属性设置时间(来自user_properties.first_open_time.set_timestamp_micros)',
  `attr_sess_set_time` DATETIME COMMENT '会话属性设置时间(来自user_properties.ga_session_id.set_timestamp_micros)',
  `analytics_stor_cd` STRING COMMENT 'Analytics存储授权状态(来自privacy_info.analytics_storage)',
  `ads_stor_cd` STRING COMMENT 'Ads存储授权状态(来自privacy_info.ads_storage)',
  `uses_tmp_tkn_cd` STRING COMMENT '是否使用临时令牌(来自privacy_info.uses_transient_token)',
  `dev_ctgy` STRING COMMENT '设备类型: mobile/tablet/desktop',
  `dev_brand_nm` STRING COMMENT '设备品牌(如 Apple)',
  `dev_model_nm` STRING COMMENT '设备型号(如 iPhone)',
  `dev_os_nm` STRING COMMENT '操作系统(如 ios/android)',
  `dev_lang` STRING COMMENT '设备语言(如 en-us)',
  `dev_tz_offset` BIGINT COMMENT '时区偏移(秒)',
  `geo_cntry` STRING COMMENT '国家(如 United States)',
  `geo_rgn` STRING COMMENT '地区(如 California)',
  `geo_city` STRING COMMENT '城市(如 Los Angeles)',
  `app_ver` STRING COMMENT '应用版本号',
  `app_id` STRING COMMENT 'Firebase应用ID',
  `app_store_nm` STRING COMMENT '应用商店(如 App Store)',
  `trfc_src_nm` STRING COMMENT '流量来源(如 google)',
  `trfc_medium` STRING COMMENT '流量媒介(如 cpc/organic)',
  `event_params_json` STRING COMMENT '事件参数完整JSON(ARRAY<STRUCT>)',
  `usr_props_json` STRING COMMENT '用户属性JSON(ARRAY<STRUCT>)',
  `ecommerce_json` STRING COMMENT '电商数据JSON(STRUCT)',
  `items_json` STRING COMMENT '商品列表JSON(ARRAY<STRUCT>)',
  `priv_info_json` STRING COMMENT '隐私信息JSON(STRUCT)',
  `event_dim_json` STRING COMMENT '事件维度JSON(STRUCT)',
  `bq_sync_time` DATETIME COMMENT 'BigQuery同步时间'
)
COMMENT '用户域-用户行为事件事务事实表(Firebase埋点)'
PARTITIONED BY (
  `ds` STRING NOT NULL COMMENT '分区日期 yyyyMMdd'
)
STORED AS AliOrc
LIFECYCLE 366;
